### ISSUE TITLE
Getting error incorrect syntax new "{" when trying to manually provision database

### ISSUE THREAD

**Issue by mzeesam** [Mimetis/Dotmim.Sync#1003] opened 2023-05-03 20:29 UTC
Hallo, 
I am getting the above error when trying to provision my server database with parameters in setup.
Please see a screenshot below:
![image](https://user-images.githubusercontent.com/31076800/236041977-6b702176-db83-4069-8701-356ce5b0a326.png)

Could there be something wrong with my 'AddCustomWhere' clause?

Thanks again in advance!

**Comment by Mimetis** [comment] 2023-10-15 11:22
Can you create a sample I can use to reproduce your error ?

**Comment by Mimetis** [comment] 2023-10-15 11:34
I've prepared a quick sample, using the same kind of filter you've used:

``` cs
var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(clientDbName));
var setup = new SyncSetup("ProductCategory");
var options = new SyncOptions { DisableConstraintsOnApplyChanges = true };

var filter = new SetupFilter("ProductCategory");
filter.AddParameter("Name", "ProductCategory", false);
filter.AddCustomWhere("{{{Name}}} = @Name or {{{side}}}.{{{sync_row_is_tombstone}}} = 1");
setup.Filters.Add(filter);
```

And it's working fine.

The issue is pretty old now, I will close it unless you still have the problem
Feel free to comment, and re-open it if needed.

**Closed by Mimetis** 2023-10-15 11:34 UTC
