### ISSUE TITLE
[Bug] Changing same field on two slaves results in different data

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#26] opened 2017-11-23 13:12 UTC
I have 3 databases: 
Master, Slave1, Slave2.
Configuration is set to: ConflictResolutionPolicy.ServerWins;

a) change the same field in Master and Slave1 -> Slave1 is aligned to Master

b) change the same field in Slave1 and Slave2 -> fields on Slave1 and Slave2 retain their values. Value of 1 is passed to Master, but not foreward to Slave2

**Comment by Mimetis** [comment] 2017-11-23 13:57
What are your providers ?
* Master is SQL Server ?
* Slave 1 and Slave 2 are SQLITE ?

I have made some tests and my tests are actually good:

**Default rows:**
MASTER   => VALUE1
SLAVE 1    => VALUE1
SLAVE 2    => VALUE1

**Then Updates:**
MASTER  => VALUE3
SLAVE 1  => VALUE4
SLAVE 2  => VALUE5
*Sync SLAVE 1*
MASTER  => VALUE3
SLAVE 1  => **VALUE3**
SLAVE 2 => VALUE5
*Sync SLAVE 2*
MASTER  => VALUE3
SLAVE 1  => **VALUE3**
SLAVE 2 => **VALUE3**

**Comment by thefonzi** [comment] 2017-11-23 14:28
This is the code, that I use: 
private static async Task DoSync()
{
    string csMaster = ConfigurationManager.ConnectionStrings["Master"].ConnectionString;
    WebProxyClientProvider serverProvider = new WebProxyClientProvider(new Uri(csMaster));
    Console.WriteLine("Master: " + csMaster);

    string csSlave = ConfigurationManager.ConnectionStrings["Slave1"].ConnectionString;
    SqlSyncProvider clientProvider1 = new SqlSyncProvider(csSlave);
    Console.WriteLine("Slave1: " + csSlave);

    csSlave = ConfigurationManager.ConnectionStrings["Slave2"].ConnectionString;
    SqlSyncProvider clientProvider2 = new SqlSyncProvider(csSlave);
    Console.WriteLine("Slave2: " + csSlave);

    // Agent
    try
    {
        SyncAgent agent1 = new SyncAgent(clientProvider1, serverProvider);

        agent1.SyncProgress += SyncProgress;
        agent1.ApplyChangedFailed += ApplyChangedFailed;

        agent2.SyncProgress += SyncProgress;
        agent2.ApplyChangedFailed += ApplyChangedFailed;

        do
        {
            Console.WriteLine("Sync Start");
            try
            {
                var s1 = await agent1.SynchronizeAsync();
                var s2 = await agent2.SynchronizeAsync();
            }
            catch (SyncException e)
            {
                Console.WriteLine(e.ToString());
            }
            catch (Exception e)
            {
                Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
            }

            Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");

        } while (Console.ReadKey().Key != ConsoleKey.Escape);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.ToString());
        Console.ReadKey();
    }

    Console.WriteLine("End");
}

**Comment by Mimetis** [comment] 2017-12-01 19:23
I will close this issue, since I'm not able to reproduce it.   
If you have still the problem, re open the issue, we will try to investigate more.

**Closed by Mimetis** 2017-12-01 19:23 UTC

**Comment by thefonzi** [comment] 2017-12-03 09:33
Hello Sebastien,
I have recorded a sample video to demonstrate the problem. In this video i use 3 MSSQL databases (DotminXAF as master and DotminXAF1, DotminXAF2 as slaves).
First I start the webserver of your samples that is slightly modified and then the client console, that syncs both slaves. 
Now at first attempt the sync works fine, but when I modify the same field on both slaves, changes of first slave are synced to master, but second slave does not get the changes! Check out the video please.

[SyncBug.zip](https://github.com/Mimetis/Dotmim.Sync/files/1524622/SyncBug.zip)
