### ISSUE TITLE
Reinit from snapshot results some empty table

### ISSUE THREAD

**Issue by tothmartonjeno** [Mimetis/Dotmim.Sync#437] opened 2021-02-09 14:05 UTC
DMS version: 0.6.1-beta-0511
Server: SQLServer
Local: SQLite console app
Table count: 40
Total rows: cca 140.000

Reinit from snapshot results some empty table and duration is longer than reinit without snapshot.
Reinit without snapshot works fine.
Reinit from snapshot using version 0.6.0 works fine.

**Comment by Mimetis** [comment] 2021-02-09 14:19
I need more details.
Looking at the discussion we have on the other issue #430, I've made some tests with your setup:

The server database table is this one:

``` sql
CREATE TABLE [dbo].[SyncLog](
	[UID] [uniqueidentifier] NOT NULL,
	[FelhasznaloKod] [int] NULL,
	[pda_sync_scope_id] [uniqueidentifier] NULL,
	[AllapotKod] [char](1) NOT NULL,
	[Manual] [bit] NULL,
	[Interactive] [bit] NULL,
	[KezdoDatum] [datetime] NULL,
	[ZaroDatum] [datetime] NULL,
	[Duration] [int] NULL,
	[TotalChangesApplied] [int] NULL,
	[TotalChangesDownloaded] [int] NULL,
	[TotalChangesUploaded] [int] NULL,
	[TotalSyncErrors] [int] NULL,
	[ErrorMessage] [nvarchar](max) NULL,
 CONSTRAINT [PK_SyncLog] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```
Everything works fine on my **Xamarin** application.

Now, using your code:

```cs
insert into SyncLog ([UID], [FelhasznaloKod], [pda_sync_scope_id], [AllapotKod], [Manual], [Interactive], [KezdoDatum])
values ('99c52a7a-2dd3-4503-8608-e5c614301387', 1, '10c52a7a-2dd3-4503-8608-e5c614301387', 'R', true, true, '')
```
Makes the sync crashes, indeed.
Because you'are inserting **Wrong Types** in your **Sqlite** table (and **SQLite** allows you to do so)

So far, I just convert your code to this code, more efficient, more secure and more performant:
``` cs
var text = "insert into SyncLog([UID], [FelhasznaloKod], [pda_sync_scope_id], [AllapotKod], [Manual], [Interactive], [KezdoDatum])" +
            "values(@id, @fk, @pdascopeid, @ak, @m, @i, @kd)";


using (var sqliteConnection = new SqliteConnection(this.settings.DataSource))
{
    var c = new SqliteCommand(text)
    {
        Connection = sqliteConnection
    };


    var p = new SqliteParameter
    {
        DbType = DbType.Guid,
        ParameterName = "@id",
        Value = Guid.NewGuid()

    };
    c.Parameters.Add(p);

    p = new SqliteParameter
    {
        DbType = DbType.Int32,
        ParameterName = "@fk",
        Value = 1
    };
    c.Parameters.Add(p);

    p = new SqliteParameter
    {
        DbType = DbType.Guid,
        ParameterName = "@pdascopeid",
        Value = new Guid("10c52a7a-2dd3-4503-8608-e5c614301387")

    };
    c.Parameters.Add(p);

    p = new SqliteParameter
    {
        DbType = DbType.String,
        ParameterName = "@ak",
        Value = "R"

    };
    c.Parameters.Add(p);


    p = new SqliteParameter
    {
        DbType = DbType.Boolean,
        ParameterName = "@m",
        Value = true

    };
    c.Parameters.Add(p);

    p = new SqliteParameter
    {
        DbType = DbType.Boolean,
        ParameterName = "@i",
        Value = true

    };
    c.Parameters.Add(p);


    p = new SqliteParameter
    {
        DbType = DbType.DateTime,
        ParameterName = "@kd",
        Value = DateTime.Now

    };
    c.Parameters.Add(p);
    sqliteConnection.Open();

    using (var t = sqliteConnection.BeginTransaction())
    {
        c.Transaction = t;

        c.ExecuteNonQuery();

        t.Commit();
    }

    sqliteConnection.Close();

}
```

From that point, the sync starts to work as expected :)

**Comment by Mimetis** [comment] 2021-02-09 20:23
You mean that there is a regression between version 0.6.1 and 0.6.0 ?
- `v0.6.0` is working fine
- `v0.6.1` is slow and some table are empty ?

If yes, are you able to create a simple repro ?

**Comment by tothmartonjeno** [comment] 2021-02-10 07:45
I can upload the progess log. It may help you. Only 4 tables contain data.
[consoleapp.log](https://github.com/Mimetis/Dotmim.Sync/files/5956526/consoleapp.log)

**Comment by Mimetis** [comment] 2021-02-10 08:16
does not help at all :)

**Comment by tothmartonjeno** [comment] 2021-02-10 08:28
After "Sending All Changes" message come 4 table "changesapplying" message. This 4 table with 23138 records is okay. But the other cca. 30 table is empty. 100000 records disappear.

Reinit without snapshot works fine.

**Comment by Mimetis** [comment] 2021-02-10 08:39
Strange...
If you are able to provide a simple repro project, will be easier to debug

**Comment by tothmartonjeno** [comment] 2021-02-15 13:45
I tested this issue. Actually each table is empty.
I changed <...>_initalize stored procedure for 4 tables after provision because I have to join to other tables to get the init rows. If I didn't change this sp-s, each table is empty with snapshot. 
Another strange thing is: size of the initialized table with snapshot and without snapshot is equal (24.133.632 bytes) but only the db which generated without snapshot contains rows in DB Browser.

**Comment by tothmartonjeno** [comment] 2021-02-15 15:30
I tried the issue with AdventureWorks database. 
I upload a .zip containing a .cs and appsetting.json. 
I run 
#1 `await service.deprovisionServer();`
#2 `await service.provisionFromServer();`
#3 `await service.createSnapshot();`
#4 `await service.synchronize();`
and the tables in .db files are empty.
[snapshot_source.zip](https://github.com/Mimetis/Dotmim.Sync/files/5982491/snapshot_source.zip)

**Comment by Mimetis** [comment] 2021-02-15 15:55
Thansk @tothmartonjeno for the sample repro !
Will try from my side, and get back to you asap

**Comment by Mimetis** [comment] 2021-02-16 14:02
Hey @tothmartonjeno !
You found a bug !
Just found the issue. Appears that combo "Snapshot + Reinitialize" ends with an empty table on the client.
The bug is fixed, I've made more checks on the tests to ensure this situation will not appear again anymore.
This issue will be fixed in the next beta version `v0.6.2`
(Or you can grab the source code from branch `v0.6.2` once all the tests are passed)

**Comment by Mimetis** [comment] 2021-02-16 15:13
Hey @tothmartonjeno 

Here is the code I'm using for testing your scenario with the source code coming from the branch `v0.6.2` :

``` cs
var clientFileName = "AdventureWorks.db";

var tables = new string[] { "Customer" };

var setup = new SyncSetup(tables)
{
    // optional :
    StoredProceduresPrefix = "ussp_",
    StoredProceduresSuffix = "",
    TrackingTablesPrefix = "",
    TrackingTablesSuffix = "_tracking"
};
setup.Tables["Customer"].SyncDirection = SyncDirection.DownloadOnly;

var options = new SyncOptions();

// Using the Progress pattern to handle progession during the synchronization
var progress = new SynchronousProgress<ProgressArgs>(s => Console.WriteLine($"{s.PogressPercentageString}:\t{s.Source}:\t{s.Message}"));

// Be sure client database file is deleted is already exists
if (File.Exists(clientFileName))
    File.Delete(clientFileName);

// Create 2 Sql Sync providers
// sql with change tracking enabled
var serverProvider = new SqlSyncChangeTrackingProvider(DBHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqliteSyncProvider(clientFileName);

// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider, options, setup);

Console.WriteLine();
Console.WriteLine("----------------------");
Console.WriteLine("0 - Initiliaze. Initialize Client database and get all Customers");

// First sync to initialize
var r = await agent.SynchronizeAsync(progress);
Console.WriteLine(r);


// DeprovisionAsync
Console.WriteLine();
Console.WriteLine("----------------------");
Console.WriteLine("1 - Deprovision The Server");

var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);
// We are in change tracking mode, so no need to deprovision triggers and tracking table. But it's part of the sample
await remoteOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable, progress: progress);

var serverScope = await remoteOrchestrator.GetServerScopeAsync(progress: progress);

serverScope.Setup = null;
serverScope.Schema = null;

// save the server scope
await remoteOrchestrator.SaveServerScopeAsync(serverScope, progress: progress);


// DeprovisionAsync
Console.WriteLine();
Console.WriteLine("----------------------");
Console.WriteLine("2 - Provision Again With New Setup");

tables = new string[] { "Customer", "ProductCategory" };

setup = new SyncSetup(tables)
{
    // optional :
    StoredProceduresPrefix = "ussp_",
    StoredProceduresSuffix = "",
    TrackingTablesPrefix = "",
    TrackingTablesSuffix = "_tracking"
};
setup.Tables["Customer"].SyncDirection = SyncDirection.DownloadOnly;
setup.Tables["ProductCategory"].SyncDirection = SyncDirection.DownloadOnly;

remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);
serverScope = await remoteOrchestrator.GetServerScopeAsync(progress: progress);

var newSchema = await remoteOrchestrator.ProvisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable, progress: progress);

serverScope.Setup = setup;
serverScope.Schema = newSchema;

// save the server scope
await remoteOrchestrator.SaveServerScopeAsync(serverScope, progress: progress);

// Snapshot
Console.WriteLine();
Console.WriteLine("----------------------");
Console.WriteLine("3 - Create Snapshot");

var snapshotDirctory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "Snapshots");

options = new SyncOptions
{
    SnapshotsDirectory = snapshotDirctory,
    BatchSize = 5000
};

remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);
// Create a snapshot
var bi = await remoteOrchestrator.CreateSnapshotAsync(progress: progress);

Console.WriteLine("Create snapshot done.");
Console.WriteLine($"Rows Count in the snapshot:{bi.RowsCount}");
foreach (var bpi in bi.BatchPartsInfo)
    foreach (var table in bpi.Tables)
        Console.WriteLine($"File: {bpi.FileName}. Table {table.TableName}: Rows Count:{table.RowsCount}");

// Snapshot
Console.WriteLine();
Console.WriteLine("----------------------");
Console.WriteLine("4 - Sync again with Reinitialize Mode");


agent = new SyncAgent(clientProvider, serverProvider, options, setup);

r = await agent.SynchronizeAsync(SyncType.Reinitialize, progress);
Console.WriteLine(r);


Console.WriteLine();
Console.WriteLine("----------------------");
Console.WriteLine("5 - Check client rows");

using var sqliteConnection = new SqliteConnection(clientProvider.ConnectionString);

sqliteConnection.Open();

var command = new SqliteCommand("Select count(*) from Customer", sqliteConnection);
var customerCount = (long)command.ExecuteScalar();

command = new SqliteCommand("Select count(*) from ProductCategory", sqliteConnection);
var productCategoryCount = (long)command.ExecuteScalar();

Console.WriteLine($"Customer Rows Count on Client Database:{customerCount} rows");
Console.WriteLine($"ProductCategory Rows Count on Client Database:{productCategoryCount} rows");

sqliteConnection.Close();
```

And here the Output:

``` bash
----------------------
0 - Initiliaze. Initialize Client database and get all Customers
0%:     8882af14-ffe7-4db1-877b-ecd820954a19:   Session Begins.
0%:     AdventureWorks: Schema Loaded For 1 Tables.
0%:     AdventureWorks: Migrated. Tables:1.
0%:     main:   Provisioned 1 Tables. Provision:Table, TrackingTable, StoredProcedures, Triggers.
30%:    AdventureWorks: [Total] Applied:0. Conflicts:0.
75%:    AdventureWorks: [Customer] [Total] Upserts:847. Deletes:0. Total:847.
75%:    AdventureWorks: [Total] Upserts:847. Deletes:0. Total:847
100%:   main:   [Customer] [Modified] Applied:(847) Total:(847/847).
100%:   main:   [Total] Applied:847. Conflicts:0.
100%:   8882af14-ffe7-4db1-877b-ecd820954a19:   Session Ended.
Synchronization done.
        Total changes  uploaded: 0
        Total changes  downloaded: 847
        Total changes  applied: 847
        Total resolved conflicts: 0
        Total duration :0:0:2.209

----------------------
1 - Deprovision The Server
0%:     AdventureWorks: Provisioned 1 Tables. Provision:TrackingTable, StoredProcedures, Triggers.

----------------------
2 - Provision Again With New Setup
0%:     AdventureWorks: Schema Loaded For 2 Tables.
0%:     AdventureWorks: Provisioned 2 Tables. Provision:TrackingTable, StoredProcedures, Triggers.

----------------------
3 - Create Snapshot
0%:     AdventureWorks: Schema Loaded For 2 Tables.
0%:     AdventureWorks: Provisioned 2 Tables. Provision:TrackingTable, StoredProcedures, Triggers.
0%:     AdventureWorks: [Customer] [Total] Upserts:847. Deletes:0. Total:847.
0%:     AdventureWorks: [ProductCategory] [Total] Upserts:41. Deletes:0. Total:41.
0%:     AdventureWorks: [Total] Upserts:888. Deletes:0. Total:888
0%:     AdventureWorks: Snapshot Created [C:\Users\spertus\AppData\Local\Temp\DotmimSync\Snapshots\DefaultScope\ALL].
Create snapshot done.
Rows Count in the snapshot:888
File: 0000_4amsi1xq_tzv.batch. Table Customer: Rows Count:847
File: 0000_4amsi1xq_tzv.batch. Table ProductCategory: Rows Count:41

----------------------
4 - Sync again with Reinitialize Mode
0%:     2a7cdd11-40c2-4182-8b33-b8b6be7bcede:   Session Begins.
0%:     main:   Migrated. Tables:2.
33%:    main:   [Customer] [Modified] Applied:(847) Total:(847/888).
35%:    main:   [ProductCategory] [Modified] Applied:(41) Total:(888/888).
35%:    main:   [Total] Applied:888. Conflicts:0.
30%:    AdventureWorks: [Total] Applied:0. Conflicts:0.
75%:    main:   [Total] Applied:0. Conflicts:0.
100%:   2a7cdd11-40c2-4182-8b33-b8b6be7bcede:   Session Ended.
Synchronization done.
        Total changes  uploaded: 0
        Total changes  downloaded: 888
        Total changes  applied: 888
        Total resolved conflicts: 0
        Total duration :0:0:0.597

----------------------
5 - Check client rows
Customer Rows Count on Client Database:847 rows
ProductCategory Rows Count on Client Database:41 rows
```

**Comment by tothmartonjeno** [comment] 2021-02-19 13:49
Thanks.
Will you upload a beta version to nuget?

**Comment by Mimetis** [comment] 2021-02-19 16:52
Before end of month I guess

**Closed** 2021-02-28 23:52 UTC
