### ISSUE TITLE
SQL Execution Timeout - 

### ISSUE THREAD

**Issue by captmomo** [Mimetis/Dotmim.Sync#309] opened 2020-08-19 02:02 UTC
```
            // If not in memory and BatchPartsInfo.Count == 0, nothing to send.
            // But we need to send something, so generate a little batch part
            if (clientBatchInfo.InMemory || (!clientBatchInfo.InMemory && clientBatchInfo.BatchPartsInfo.Count == 0))
            {
                var changesToSend = new HttpMessageSendChangesRequest(ctx, scope);

                if (this.Converter != null && clientBatchInfo.InMemoryData != null && clientBatchInfo.InMemoryData.HasRows)
                    this.BeforeSerializeRows(clientBatchInfo.InMemoryData);

                var containerSet = clientBatchInfo.InMemoryData == null ? new ContainerSet() : clientBatchInfo.InMemoryData.GetContainerSet();
                changesToSend.Changes = containerSet;
                changesToSend.IsLastBatch = true;
                changesToSend.BatchIndex = 0;

                // serialize message
                var serializer = this.SerializerFactory.GetSerializer<HttpMessageSendChangesRequest>();
                var binaryData = await serializer.SerializeAsync(changesToSend);

                await this.InterceptAsync(new HttpMessageSendChangesRequestArgs(binaryData), cancellationToken).ConfigureAwait(false);

                httpMessageContent = await this.httpRequestHandler.ProcessRequestAsync<HttpMessageSendChangesResponse>
                    (this.HttpClient, this.ServiceUri, binaryData, HttpStep.SendChanges, ctx.SessionId, scope.Name,
                     this.SerializerFactory, this.Converter, this.Options.BatchSize, cancellationToken).ConfigureAwait(false);

            }
```

The sql execution times out during this step often. Any advice on how to handle this? I've tried setting batch size to 500, and it still fails. It's strange because sometimes it works, sometimes it doesn't. My schema contains 19 tables.

**Comment by Mimetis** [comment] 2020-08-19 09:56
Is this timeout happening on the first synchronization ?

The first sync, depending on your database, can be really heavy for your server.
Sometimes it can leads to timeout, because the generation of the batches are too long.

You should increase the timeout, or use the snapshot functionnality:
- https://dotmimsync.readthedocs.io/Snapshot.html
- https://dotmimsync.readthedocs.io/Timeout.html

**Comment by captmomo** [comment] 2020-08-19 12:50
Intermittently, surprisingly the initial sync is usually successful.
Sometimes taking less than a minute to sync 100mb of data.

However it sometimes happens when I try to create a snapshot. Upon
investigation, I’m beginning to suspect there could be other software
writing to the database causing locks. I will try to make snapshots again
and see if it helps. Thanks again for your help and advice.

**Comment by Mimetis** [comment] 2020-08-19 12:52
Let me know :)
I close the issue, but feel free to re open it, if the problem is coming from the `DMS` framework

**Closed by Mimetis** 2020-08-19 12:52 UTC
