### ISSUE TITLE
Upgrading from 0.9.4 to 1.2.0 is giving me Dotmim.Sync.HttpHeaderMissingException: 'Header dotmim-sync-session-id is missing.' in postman

### ISSUE THREAD

**Issue by Tuytje** [Mimetis/Dotmim.Sync#1258] opened 2024-10-12 19:26 UTC
I have been running v0.9.4 and when I try to bring my webserver to the current version it is giving me "Dotmim.Sync.HttpHeaderMissingException: 'Header dotmim-sync-session-id is missing.'" when trying a post from postman.

When following the sourcecode it seems only logical since in the first lines of 'WebServerAgent.HandleRequestAsync' it checks for these variables in the header. Are these normally sent by the cllient? If so, how does one go about testing the call in postman?

This is my POST code in the controller where WebServerAgent is of type Dotmim.Sync.Web.Server.WebServerAgent
```
        [HttpPost()]
        public async Task Post()
        {
            try
            {
                // handle request
                await WebServerAgent.HandleRequestAsync(this.HttpContext);
            }
            catch (Exception ex)
            {
                await WebServerAgent.WriteExceptionAsync(this.HttpContext.Request, this.HttpContext.Response, ex);
            }
        }
```

Thank you.

**Comment by Mimetis** [comment] 2024-10-16 09:46
Each time you are doing a sync through DMS, the framework is using a GUID to identify the whole sync pipeline and all the requests done to the server.

You can see the code in the `Dotmim.Sync.Web.Server` project, in the [HandleRequestAsync](https://github.com/Mimetis/Dotmim.Sync/blob/ac25fc08042c5c1da26cb137b82426f1bf491bb4/Projects/Dotmim.Sync.Web.Server/WebServerAgent.cs#L261) method:

``` cs
var httpRequest = httpContext.Request;
var httpResponse = httpContext.Response;

TryGetHeaderValue(httpContext.Request.Headers, "dotmim-sync-serialization-format", out var serializerInfoString);
TryGetHeaderValue(httpContext.Request.Headers, "dotmim-sync-converter", out var cliConverterKey);
TryGetHeaderValue(httpContext.Request.Headers, "dotmim-sync-version", out string version);

if (!TryGetHeaderValue(httpContext.Request.Headers, "dotmim-sync-session-id", out var sessionId))
    throw new HttpHeaderMissingException("dotmim-sync-session-id");

if (!TryGetHeaderValue(httpContext.Request.Headers, "dotmim-sync-scope-name", out var scopeName))
    throw new HttpHeaderMissingException("dotmim-sync-scope-name");

if (!TryGetHeaderValue(httpContext.Request.Headers, "dotmim-sync-step", out string iStep))
    throw new HttpHeaderMissingException("dotmim-sync-step");
```

Basically:
- `dotmim-sync-session-id` is `GUID`
- `dotmim-sync-scope-name` is the scope name (generally "DefaultScope")
- `dotmim-sync-step` is the current [HttpStep](https://github.com/Mimetis/Dotmim.Sync/blob/ac25fc08042c5c1da26cb137b82426f1bf491bb4/Projects/Dotmim.Sync.Web.Client/HttpStep.cs#L6) step serialized as an int.

If you want to test the method, just add these headers: a random `GUID`, a scope name called "**DefaultScope**" is fine, and for the `HttpStep`, the easiest one is to use `2` (this step is ensuring that the schema exists on the server)
You will need to pass some extra info like serialization method, but nothing to fancy.

Then you will need to pass a body to your request.For the step 2, The body is a `HttpMessageEnsureScopesRequest` class.

Here is a full example:

``` cs
HttpClient client = new HttpClient();
var sessionId = Guid.NewGuid();
var scopeName = SyncOptions.DefaultScopeName;

HttpMessageEnsureScopesRequest message = new HttpMessageEnsureScopesRequest
{
    SyncContext = new SyncContext(sessionId, scopeName)
};

client.DefaultRequestHeaders.Add("dotmim-sync-session-id", sessionId.ToString());
client.DefaultRequestHeaders.Add("dotmim-sync-scope-name", scopeName);
client.DefaultRequestHeaders.Add("dotmim-sync-step", "2");
client.DefaultRequestHeaders.Add("dotmim-sync-serialization-format", "{\"SerializerKey\":\"Json\",\"ClientBatchSize\":1000}");

var body = SerializersFactory.JsonSerializerFactory.GetSerializer().Serialize(message);

var response = await client.PostAsync(serviceUri, new ByteArrayContent(body));

```

**Comment by Tuytje** [comment] 2024-10-17 19:14
Thank you for the reply.

I think I bumped into a bug in the 'Dotmim.Sync.Core\Orchestrators\Provision\BaseOrchestrator.Provision.cs' class. It crashes on line 228 (line in bold) with the following exception: System.InvalidCastException: 'Unable to cast object of type 'Dotmim.Sync.SyncTable[]' to type 'System.Collections.Generic.List`1[Dotmim.Sync.SyncTable]'.'
```
if (scopeInfo.Schema != null)
{
    schemaTables = scopeInfo.Schema.Tables.SortByDependencies(tab => tab.GetRelations().Select(r => r.GetParentTable())).ToList();
}
else
{
    schemaTables = [];
    foreach (var setupTable in scopeInfo.Setup.Tables)
        **((List<SyncTable>)schemaTables).Add(new SyncTable(setupTable.TableName, setupTable.SchemaName));**
}
```

This makes sense since the 'schemaTables' is defined as an array, but cast to a List. I guess it should have been cast to an IList?

I hope you find the time to fix this, since it is blocking me at the moment (or can I work around this?)

**Comment by Mimetis** [comment] 2024-10-17 22:06
Can you share a sample that reproduce the error ?

**Comment by Tuytje** [comment] 2024-10-18 19:46
Not really since it is in the Deprovision step (trying to update the database from 0.9.4 to the most recent I take it) and the database is not a small one. 

I have uploaded a screenshot that shows the place where it will crash (F10 would crash it, as seen by the second watch line), with a watch on the variable that will crash:
![image](https://github.com/user-attachments/assets/bf233ec4-571f-448a-9d97-10490bd9e462)

Any other screenshots I could take?

**Comment by Mimetis** [comment] 2024-10-18 20:53
The problem is that I don't know how to reproduce your error, unfortunately.

Until I know how to reproduce the error, it will be difficult for me to make any fix....

**Comment by Mimetis** [comment] 2024-10-18 20:57
You can try the last commit to see if it's resolving your issue

**Comment by Tuytje** [comment] 2024-10-19 14:26
I have download your latest code, verified I had the change (IEnumerable -> List) and plugged it in. That specific error went away, so good fix :)
I do have another one now: 
![image](https://github.com/user-attachments/assets/b755b038-6bfc-404c-b313-ca9982a544fd)

Following the code it could be I need to supply a 'dotmim-sync-serialization-format'. I take it that this also comes from the client, but couldn't figure out what I should supply here (still running from postman, where I have added 'dotmim-sync-session-id', 'dotmim-sync-scope-name', 'dotmim-sync-step' following your instructions).

**Comment by Mimetis** [comment] 2024-10-19 15:40
If you look at my code, you will notice that I have a specific header with the serializer option: 
``` cs
client.DefaultRequestHeaders.Add("dotmim-sync-serialization-format", "{\"SerializerKey\":\"Json\",\"ClientBatchSize\":1000}");
```

**Closed** 2024-10-20 17:44 UTC

**Comment by Tuytje** [comment] 2024-10-21 07:49
Any idea when you could do a release on nuget with the fix (could be a beta release)?

**Comment by Mimetis** [comment] 2024-10-21 13:45
I will publish a beta version this week :)

**Comment by Mimetis** [comment] 2024-10-21 22:02
published !

**Comment by Tuytje** [comment] 2024-10-23 06:42
Thank you!
