### ISSUE TITLE
0.4.3 Sqlite file gets out of sync

### ISSUE THREAD

**Issue by dgrothman** [Mimetis/Dotmim.Sync#300] opened 2020-07-22 00:52 UTC
I am running dotmim 0.4.3 currently and has been running well, I have ran into an issue with a single instance where the sqlite database on the client has information that is not on the server, but the sync doesn't "see" it and therefore it never gets pushed to the cloud database (azure sql). If I try and sync the agent using syncType.ReinitializeWithUpload the data gets destroyed. Is there any way I can force it to recheck the table the data is in and upload it? I have the sqlite file backed up, so I can try making changes in the sqlite file itself if needed, but I don't understand how the tracking tables work.

**Comment by gentledepp** [comment] 2020-07-22 06:38
TLNR;
You need to do a normal sync in those cases, but reset the local timestamp to 0 (lastSyncTimestamp in _scopeInfo table), so that all changes are resent. This will cause a whole lot of sync conflicts and take a while, but it will work.


If you are using "ReinitializeWithUpload", the client will only send *pending* changes to the server. Thereafter it will delete all local data (thus destroying your forgotten local changes) and re-download all data from the server.
Due to a misconception in the sync framework, the client can "overlook" pending changes and never send them.

Have a look at my explanation titled 
#### 4 Warning using SqliteProvider due to transaction-overlappings (no timestamp exists on sqlite)
here: https://github.com/Mimetis/Dotmim.Sync/issues/255


# Our current solution
We use a multiple reader/single writer lock in C# to ensure, that two sqlite transactions cannot overlap. The (single) writer access is taken by the dotmim.sync while all other transactions (any application access to the database) uses the reader lock.
This ensures that dodmim.sync cannot collect any local changes, while some other transaction has not yet committed.

# The best solution
...would be if dotmim.sync would opt to switch back to the same change detection approach that the original Microsoft Sync Framework used locally: (As far as I remember) it had a `dirty` column in the `_tracking` tables and did not use a `lastSyncTimestamp`. That way, even if transactions overlapped, a subsequent sync would detect `dirty` rows and send them.
@Mimetis  what do you think? This causes real headache. As SQLite does not have a real `timestamp` and no `min_active_rowversion` I guess this is the only real option. 
I guess it won't hurt, if we'd introduce an additional `dirty` column **only for SQLite**.

**Comment by Mimetis** [comment] 2020-07-22 09:09
@dgrothman 

A row that "*is tracked*" has its own corresponding row in the `tracking_table`.

Let's say for example, in the **Customer** table, for one row:
![image](https://user-images.githubusercontent.com/4592555/88154723-810a6180-cc07-11ea-8941-cf2744ab5dc7.png)

You have the corresponding row in **Customer_tracking**:
![image](https://user-images.githubusercontent.com/4592555/88154825-9aaba900-cc07-11ea-9a71-b33599f645c5.png)

Here are the desciption of all columns:

> **Be Careful**: This explanation applies only from the client database perspective. The server side is a little bit more complex.

- **CustomerID**: Primary keys of the **Customer** table, that is used as primary key as well in **Customer_tracking**. Depending on the reference table, you can have multiple columns.
- **udapte_scope_id**: Scope who have altered the row. we have, from a client perspective, two scopes: local (client) and remote (server). If the guid is set to `00000000-0000-0000-0000-000000000000` the update is coming from the server. if the guid is set to `NULL`, the update is local
- **timestamp**: unique bigint representing the time when the row was updated
- **sync_row_is_tombstone**: bit indicating if the reference row has been deleted or not.
- **last_change_datetime**: Human readable last change datetime (not used in the framework)

So far, the most important to understand is the use of both **timestamp** and **update_scope_id**:
A row is marked as *to be synchronized* if:
- **timestamp** value is superior to last sync timestamp (stored in **scope_info** table)
- the update is local (**udapte_scope_id** is set to `NULL`)

For instance, this row will never be uploaded:

![image](https://user-images.githubusercontent.com/4592555/88155584-8a47fe00-cc08-11ea-8b48-321b5a76f93f.png)

But if I make a change in the **Customer** table, the tracking is changing to:

![image](https://user-images.githubusercontent.com/4592555/88155652-a5b30900-cc08-11ea-832b-05bc24174e23.png)

Now, since the row has been updated after the last sync AND the update has been made locally, the row will be sent to the server



To resolve your issue, you should look at this row, if it's present or not.
If not, you can make a simple update of your table, the **update_trigger** will automatically update the row values (or create them) in the tracking table.

the trigger looks like this:

``` sql
UPDATE [Customer_tracking] 
SET [update_scope_id] = NULL -- scope id is always NULL when update is made locally
 ,[timestamp] = replace(strftime('%Y%m%d%H%M%f', 'now'), '.', '')
 ,[last_change_datetime] = datetime('now')
Where [Customer_tracking].[CustomerID] = new.[CustomerID];
 
INSERT OR IGNORE INTO [Customer_tracking] (
	[CustomerID], [update_scope_id], [timestamp], [sync_row_is_tombstone], [last_change_datetime]
) 
VALUES (
	new.[CustomerID], NULL, replace(strftime('%Y%m%d%H%M%f', 'now'), '.', ''), 0, datetime('now')
);
```

Just for your info, the select command, when a sync tries to get the **changes** from a table, for SQLITE, looks like this (I removed statements for clarity):

``` sql
SELECT columns
FROM [Customer] [base]
RIGHT JOIN [Customer_tracking] [side] ON [base].[CustomerID] = [side].[CustomerID]
WHERE (
	[side].[timestamp] > @sync_min_timestamp
	AND ([side].[update_scope_id] <> @sync_scope_id OR [side].[update_scope_id] IS NULL)
)
```
As you can see, the `WHERE` clause is summarizing what I said previously

Most probably in your situation, you have a row that has been updated at the **exact same time** as a in progress sync.
Not sure about that, I don't have enough information to debug your case.

As @gentledepp mentioned, since we do not have a real **timestamp** column type and **min_active_rowversion** function, it's really complicated to ensure the transactional thing.
A good sync to do is : Do not allow any modification of the database when making a sync. 

@gentledepp: Regarding the **dirty** column, it will not help a lot (well in my opinion, at least ;) )

If you read carefully my explanations, we can say that the column **update_scope_id** is *playing* the same role as your **dirty** column:
- When making a local change, make **dirty** to `true`
Is equal to
- When making a local change, make **udapte_scope_id** set to `NULL`.

To be honest, I have tested a version of `DMS` using a *kind of* dirty column, but as far as I remember, it did not help.

**Comment by gentledepp** [comment] 2020-07-23 06:40
Well, I disagree but I would let you convince me.
Let's play this through in a thought experiment:


So... on MSSQL, we do have the `min_activerowversion` that gives you the *lowest* timestamp that is currently being used in a transaction. So by using `min_activerowversion - 1` you get **the lowest timestamp not currently hidden by a transaction** and when storing it as `sync_timestamp`, you can be sure, that next time, when you only send incremental changes `> sync_timestamp` you will not miss any changes.

Now, on SQLite you do not have such a thing. Therefore you build the timestamps yourself.

## using `timestamp`
Now what could happen is:
* row "customer A" has timestamp `t1`
* row "customer B" has timestamp `t2` but is hidden because it is still used in tx1 which is **not** yet committed
* row "customer C" has timestamp `t3` 

Now you sync at `t4` and send all changes (except "customer B" which is still hidden by tx1) to the server. 
Thereafter, you store `t4` happily and think that everything went fine.
However, "customer B" will **never** be sent to the server.

## using `dirty` 
Now, let's see how this would work with a `dirty` column:
* row "customer A" has timestamp `t1` and is `dirty`
* row "customer B" has timestamp `t2` and is `dirty` but is hidden because it is still used in tx1 which is **not** yet committed
* row "customer C" has timestamp `t3` and is `dirty`

Now you again sync at `t4` and send all changes (except "customer B" which is still hidden by tx1) to the server.
Thereafter, when you sync again, tx1 will eventually have been committed and you will see that row "customer B" is `dirty` so you won't miss it.

There is, however, a downside to this: Using the `dirty` column, Dotmim.Sync would have to modify each local metadata row in order to set `dirty=0` once the data was successfully sent to the server. So this may be a performance penalty which is negligible given the fact that it is a simple and batchable SQL command: "update customer_tracking set dirty = 0 where id in (@aLotOfIds)"


What are your thoughts? :-)

**Comment by Mimetis** [comment] 2020-07-23 09:37
Well in your scenario with **timestamp**, regarding how the `DMS` framework is working, your *customer B* will be sent anyway :) 

The fact is that the `last_sync_timestamp` saved in the `scope_info` is always fetch from the client database **at the begining** of the sync process and not at the **end** of it (and it will be eventually saved at the end)
That way, you are sure that an *transaction* happening during an in *going sync* will be retrieved on the next sync

Let me explain:

- Client launches a Sync
- Client gets the last time stamp from the last sync, stored in `scope_info` table, let's say `T0`. this value is the `@sync_min_timestamp`
- Client gets the last time stamp from the database, let's say `T10`. this value will be saved at the end of the process
- Client gets all changes from database that have > `T0` AND changes have been made locally 
`[side].[timestamp] > @sync_min_timestamp AND ([side].[update_scope_id] <> @sync_scope_id OR [side].[update_scope_id] IS NULL)`
- During this time, another transaction, committed, inserts a line, it will be `T11`
- Even though, we have another transaction on going, not commited
- Client ends the sync, getting rows from server
- Client saves the last time stamp in the `scope_info` table, replacing `T0` with `T10`
- The transaction commits with timestamp `T12`

As you can see, using a timestamp retrieved at the begining of the process is a good solution to be sure all rows will be retrieved in the good way

By the way, we do not use the `min_active_rowversion` otherwise the change tracking system will not work correctly.
Instead we are using the `@@DBTS` function again.
See class `SqlScopeInfoBuilder`:

``` cs
// UPDATE Nov 2019 : We don't use min_active_rowversion anymore, since we are in a transaction
// and we still need the last row version, so check back to @@DBTS
var commandText = "SELECT @sync_new_timestamp = @@DBTS";
```

**Comment by gentledepp** [comment] 2020-07-23 11:15
> During this time, another transaction, committed, inserts a line, it will be T11
Because the "spritf" function you are using for generating these pseudo timestamps is **not** evaluated when the transaction commits, but when the row is inserted/updated.
So what happend (and this can be proven) in our case is:

- Client launches a Sync
- Client gets the last time stamp from the last sync, stored in scope_info table, let's say T0. this value is the @sync_min_timestamp
- **another transaction** inserts a row at **T9** which is not yet visible to dotmom.sync as the transaction is **not yet committed**
- Client gets the last time stamp from the database, let's say T10. this value will be saved at the end of the process
- Client gets all changes from database that have > T0 AND changes have been made locally
- [side].[timestamp] > @sync_min_timestamp AND ([side].[update_scope_id] <> @sync_scope_id OR [side].[update_scope_id] IS NULL)
- During this time, another transaction, committed, inserts a line, it will be T11

And in **exactly these cases** the local change inserted at T9 will *never* be sent to the server. It took us months to track down and verify this issue and we finally solved it with our MultipleReaderSingleWriterLock!

> By the way, we do not use the min_active_rowversion otherwise the change tracking system will not work correctly.
Ok... that sounds weirdly interesting. I cannot wrap my head around this at the moment, but I will take a closer look

**Comment by Mimetis** [comment] 2020-07-23 11:39
Thanks @gentledepp 
You should be right on that, I guess.

Unfortunatelly, I don't have a solution for that, at the moment.
Once again, I think making a sync when no transaction are in progress is a good pattern to follow :) 
Especially with SQLITE.

Your **MultipleReaderSingleWriterLock** is good also, but not depending on `DMS`

In my opinion, the `Dirty` flag won't help here either. (your thought ?)

Also, could be a good thing to create the test for this particular use case and see if we can resolve it in any way

**Comment by gentledepp** [comment] 2020-07-23 12:19
Well, the `dirty` column would definitely be a solution.

8. Client launches a Sync
9. another transaction inserts a row *R9* at T9 which is not yet visible to dotmom.sync as the transaction is not yet committed
10. Client gets all changes from database that have using `dirty = 1` 
11. During this time the other transaction is committed and *R9* becomes visible
12. Once the client gets the confirmation of the server, it resets the `dirty` column of all the rows it just sent

15. in the next sync, because we are *not* filtering based on a timestamp > T10, *R9* will be picked up and sent to the server.


Now you may spot the difficulty here:
How do we make sure that at step **12** we do NOT reset the `dirty` flag of **R9**
-> we do not just run a bulk `update xy_tracking set dirty = 0` but only set those rows `dirty=0` that we just sent

But then there can still be one minor overlapping!
Let's replay the above example:

7. **a transaction commits that modified the row *R9* **
8. Client launches a Sync
9. **another transaction updates row *R9* at T9** which is not yet visible to dotmim.sync as the transaction is not yet committed
10. Client gets all changes from database that have using `dirty = 1` 
11. During this time the other transaction is committed and *R9* becomes visible
12. Once the client gets the confirmation of the server, it resets the `dirty` column of all the rows it just sent

So in **that** case, because *R9* was already dirty before the sync, the framework would reset its `dirty` flag at 12 **even though the latest change that was committed at 11 has not been sent**

## To mitiate this, there are two possibilities:

a. Keep a transaction running during the sync between 10 and 12. This would actively block the other transaction from modifying the `dirty` column of any rows that are being sent to the server. However, it could result in a long running transaction (as it stays active while all data is serialized and sent to the server - this could take several seconds to minutes) and thus to sqlite Busy exceptions and app crashes

b. introduce another tracking table column `syncsession` which will be set at 10 when dotmim.sync selects the changes using some `Guid.NewGuid`. (let's call it **G7**)
The insert/update/delete triggers always set this `syncsession` column to `NULL`.
So when at 11, the other transaction is committed, the tracking table of *R9* won't have a value in `syncsession` anymore.
At 12, we reset the `dirty` flag of all the tracking table entries, where the `sessionid` is **G7**
This is a very simple update statement and fast as we do not even need to include the identities of the uploaded records. Just ´Update xy_tracking set dirty = 0, sessionid = null where sessionid = **G7`

So all in all, I'd say that the (b) approach is the bulletproof one where you won't need any locking any longer and your local database also won't be blocked.

**Comment by gentledepp** [comment] 2020-07-23 12:36
>By the way, we do not use the min_active_rowversion otherwise the change tracking system will not work correctly.
Instead we are using the @@DBTS function again.

I just ran the test -> green
Then modified GetLocalTimeStampAsync to use 
```

            // UPDATE Nov 2019 : We don't use min_active_rowversion anymore, since we are in a transaction
            // and we still need the last row version, so check back to @@DBTS
            var commandText = "SELECT @sync_new_timestamp = min_active_rowversion() - 1";

```
-> still green.

So the test does not cover the issue that it should.


Also, I do not get why you are not using `min_active_rowversion()-1` anymore as it was built for this exact purpose.
- using `min_active_rowversion()-1` you may get some row being sent twice in two sequential syncs. That may not be optimal, but at leas you will never **fail to send server side changes** to the client
_ using `@@DBTS` the exact same issue that I descrived before for SQLIte may happen: As several timestamps are not yet committed, you won't see them and in the next sync, the timestamp may already be too high so those rows will **never** be sent to any client. 👎😢

**Comment by Mimetis** [comment] 2020-07-23 12:54
Don't remember exactly but it seems to me that it won't work with `SqlServerTrackingChange` provider.

**Comment by dgrothman** [comment] 2020-07-23 20:06
Thank you this has been very helpful. I found that the sqlite database had the new data but the trigger had not run (or failed to run) so the tracking table didn't have a row for it. Do you have any recommendations for next steps to troubleshoot why the trigger is not able to or fails to create the new row in the tracking table when a new record is added? Could it be an issue that the way the data is added to the sqlite file is via Entity Framework Core and it is fighting with dotmim for write access? I am not getting data loss though, I just find that the new record fails to write to the sqlite file but I am finding that the tracking table fails to update and then will not track any changes from then on

**Comment by Mimetis** [comment] 2020-07-23 21:01
I don't know, and I don't see any reason why the trigger did not fired...
maybe @gentledepp has faced the same issue ?

@dgrothman Are you able to reproduce this behavior easily ? or is it random ?

**Comment by dgrothman** [comment] 2020-07-23 21:25
I will work on looking into being able to reproduce it myself manually. I have a db file that is in that state (there is table data that hasn't triggered new data in the tracking table, i dont know if that will help.

**Comment by Mimetis** [comment] 2020-07-23 21:28
Well just need a sample to be able to repro this "bug" :)

**Comment by gentledepp** [comment] 2020-07-24 06:18
I cannot remember any case where the trigger in a SQLite database did not fire correctly so I doubt that this is a bug of Dotmim.Sync. Can it be that you provisioned the sync scope *after* inserting that row?
We've had dozens of sqlite database sent from users to analyse and never had any issue in the past 2 years

**Comment by Mimetis** [comment] 2020-07-27 12:31
God I've written a full post, and it seems I did NOT PUSH THE COMMENT BUTTON ....
I will recreate it ...

**Comment by Mimetis** [comment] 2020-07-27 12:48
@gentledepp 

I'm trying to recreate a sample where the bug *is happening* ..
But I did not succeeded yet :)

IF we get all your steps, with **T0**, **T9** and **T10** where you say

> - Client launches a Sync
> - Client gets the last time stamp from the last sync, stored in scope_info table, let's say T0. this value is the @sync_min_timestamp
> - another transaction inserts a row at T9 which is not yet visible to dotmom.sync as the transaction is not yet committed

The **another transaction** barely **can't** insert the row in, let's say `Address` and `Address_tracking`, because the `DMS` framework has an **opened and locked transaction** on these tables...

I'm really trying to hook the system, bu did not find a way to make this ... fail :)

## Repro

Here is my reproduction that you will find in the last commit

https://github.com/Mimetis/Dotmim.Sync/blob/72da7c8ac51935330662ee98d95e7a7a4c03c400/Samples/Dotmim.Sync.SampleConsole/Program.cs#L524

## Long running insert into sqlite

The idea is to insert a row in sqlite, that will take a bunch of times, before the transaction commits:

``` cs
private static async Task LongInsertIntoSqliteAsync(DbConnection connection)
{
    var addressline1 = Path.GetRandomFileName().Replace(".", "").ToLowerInvariant();

    var command = connection.CreateCommand();
    command.CommandText =
        $"Insert into Address (AddressLine1, City, StateProvince, CountryRegion, PostalCode, rowguid, ModifiedDate) " +
        $"Values ('{addressline1}', 'Toulouse', 'Haute Garonne', 'Occitanie', '31000', '{Guid.NewGuid()}', '2020-02-02');" +
        $"Select timestamp from Address_tracking where AddressID = (Select AddressID from Address where AddressLine1 = '{addressline1}')";

    connection.Open();

    using (var transaction = connection.BeginTransaction())
    {
        command.Transaction = transaction;
        Console.ForegroundColor = ConsoleColor.Red;
        Console.WriteLine($"[{DateTime.Now:ss.ms}] - Inserting row ");

        var ts = await command.ExecuteScalarAsync();

        Console.WriteLine($"[{DateTime.Now:ss.ms}] - SQLite Timestamp inserted (T9) : " 
            + ts.ToString().Substring(ts.ToString().Length - 4, 4));

        Console.WriteLine($"[{DateTime.Now:ss.ms}] - Waiting 10 sec before commit");
        await Task.Delay(10000);

        transaction.Commit();
        Console.WriteLine($"[{DateTime.Now:ss.ms}] - Transaction commit");
        Console.ResetColor();

    }
        connection.Close();
}
```

As you can see here, I'm inserting a row in `Address` and I'm waiting *after* the insert, at last 10 sec before committing
The statement returns what we called **T9**

## Parrallel sync 

In the main method I have 3 syncs:
- First one to initialize everything
- Second one to create the situation
- Third one to see a last sync result

Nothing really interesting in 1st and 3rd sync.

Now the 2nd sync, I will just launch, in parrallel, the sync and the sqlite long running insertion:

``` cs
agent.LocalOrchestrator.OnDatabaseChangesSelecting(async dcsa =>
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"[{DateTime.Now:ss.ms}] - Last Sync TS start (T0) : " + dcsa.ChangesRequest.LastTimestamp.ToString().Substring(dcsa.ChangesRequest.LastTimestamp.ToString().Length - 4, 4));
    Console.ResetColor();
});

agent.LocalOrchestrator.OnDatabaseChangesSelected(dcsa =>
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"[{DateTime.Now:ss.ms}] - Last Sync TS for next run (T10) : " + dcsa.Timestamp.ToString().Substring(dcsa.Timestamp.ToString().Length - 4, 4));
    Console.ResetColor();
});


// Using the Progress pattern to handle progession during the synchronization
var progress = new SynchronousProgress<ProgressArgs>(s =>
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"[{DateTime.Now:ss.ms}] - {s.Context.SyncStage}:\t{s.Message}");
    Console.ResetColor();
});

var t1 = LongInsertIntoSqliteAsync(clientProvider.CreateConnection());
var t2 = agent.SynchronizeAsync(progress);

await Task.WhenAll(t1, t2);
Console.WriteLine(t2.Result);

```

And here is the final output, with coloration:

![image](https://user-images.githubusercontent.com/4592555/88542956-8d335c00-d017-11ea-8bf7-8e7e19ab3128.png)

As you can see, the sync has began at the same time as the sqlite insert
BUT...
The loading part (from `DMS`) is waiting that the lock is removed from the table, hold by the sqlite statement.

I've even tried to launch of the sqlite statement after DMS has read the data, but once again, since DMS is fully in a transaction, sqlite is just waiting the lock to be unlocked.

The only weird thing i've finally succeded to do, is to have a deadlock :D

Once again, I agree with you on the scenario, but I'm not able to reproduce it, at least in the last `DMS` version

**Comment by Mimetis** [comment] 2020-08-30 22:17
Will close this issue until one of you wants to re-open it ;)

**Comment by gentledepp** [comment] 2020-09-28 15:05
I now had the time to look into your repro and saw that it does not work - just as you mentioned.
However, I found out, why **we** do have this issue!

We are using WAL (write-ahead logging) as it was so by-default implemented by [sqlite-net](https://github.com/praeclarum/sqlite-net)
This mode allows multiple readers and writers *simultaneously*

So this is how the issue can come up.

Honestly, I would like to keep using WAL as it is just so much faster in most cases.
Have a look at the SQLite documentation on [Isolation And Concurrency](https://sqlite.org/isolation.html) and search for **wal**:

> WAL mode permits simultaneous readers and writers. It can do this because changes do not overwrite the original database file, but rather go into the separate write-ahead log file. That means that readers can continue to read the old, original, unaltered content from the original database file at the same time that the writer is appending to the write-ahead log. In WAL mode, SQLite exhibits "snapshot isolation". When a read transaction starts, that reader continues to see an unchanging "snapshot" of the database file as it existed at the moment in time when the read transaction started. Any write transactions that commit while the read transaction is active are still invisible to the read transaction, because the reader is seeing a snapshot of database file from a prior moment in time.

I am currently trying to modify your repro so that it actually breaks. Wish me luck!

**Comment by Mimetis** [comment] 2020-09-30 07:05
God, if you find a way to reproduce this issue, it could be a BIG step forward for DMS stability !!!
I wish you all the luck I possibly can !!! :)

**Comment by gentledepp** [comment] 2020-10-05 14:19
Hmmm... I am really biting my teeth out on this.
It seems that you are right and I was wrong:
Sqlite allows for multiple concurrent transactions, if they are only **reading** data.
As soon as there is a **write transaction**, however, the isolation level is `Serialized`. This means that only one connection can write to the database at a time....

I tried to reproduce this with `PRAGMA journal_mode wal` but it did not change anything.
I tried to reproduce this using [sqlite-net](https://github.com/praeclarum/sqlite-net), as I assumed it may be due to an implementation detail.
However, when a `SQLite.SQLiteConnection` currently has a **write transaction** open, *DMS* correctly blocks....

However, as we still have this very issue occasionally, I will keep on digging.

**Comment by gentledepp** [comment] 2020-10-06 08:38
Update: I am now even down to Microsoft.Data.SQLite level to reproduce this.
Still without luck.

What was confusing is, that you *can* actually have to concurrent transactions *as long as* both of them only **read** from the database.
As soon as one also **writes*, the other transaction will get a  `Busy` exception. 
This works also across libraries (e.g. one connection from sqlite-net, one from Microsoft.Data.Sqlite)

A sample of this "upgrade to write transaction" behavior is very [**well documented here**](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/transactions)

**Comment by Mimetis** [comment] 2020-10-06 09:16
Hey @gentledepp 
Thanks you so much for the amount of work / help you've done on this one !

I think we can make the conclusion that everything is fine if we are using correctly the transaction read / commit :)

From the doc you mention:

> Transactions are serializable by default in SQLite. This isolation level guarantees that any changes made within a transaction are completely isolated. Other statements executed outside of the transaction aren't affected by the transaction's changes.

Serializable is the most constraint mode, so I guess we are good :)

**Comment by gentledepp** [comment] 2020-10-06 10:45
Yes, but please make sure, that as soon as you upgrade to [Microsoft.Data.Sqlite 5.0 ](https://www.bricelam.net/2020/09/23/microsoft-data-sqlite-5-0.html)(which is in RC now and will be shipped in November 2020), you verify, that all of dotmim.sync transactions (**especially the one selecting local changes**) is **not** a [deferred transaction](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/transactions#deferred-transactions)

Otherwise, this would introduce exactly the bug I described!

I just assumed that it would be possible, because sqlite-net supports deferred transactions **implicitly** and since 2015...

**Comment by Mimetis** [comment] 2020-10-06 10:48
Ok I'll reopen the issue to get the trace of it

**Comment by gentledepp** [comment] 2020-10-13 11:51
🎉 Heureka! I finally found the issue and could even reproduce it in the latest version of DMS on the master branch!

The issue is, that the `WebServerOrchestrator` just creates a new `clientBatchInfo` if it is null.
The issue with this is: If you send changes in batches and the server session is lost (e.g. due to an ApplicationPool recycle or because the Redis cache was cleared), it will just forget all the batches that were already sent during the ongoing session!



See the following sequencediagram for clarification:
```mermaid
sequenceDiagram
    participant Client
    participant Server
    loop GetLocalChanges
        Client->>Client: create 2 batch files
    end
    Client->>Server: Send batch #0
    Note right of Server: session is lost => clientBatchInfo is null
    Client->>Server: Send batch #1
    Client->>Server: Send (last) batch #2
    loop ApplyChanges
         Server->>Server: deserialize all batches and apply to database
         Note right of Server: Because the server does not throw an exception if the clientBatchInfo is null although the batchIndex is not 0, it will carry on and insert the changes of batch #1 and batch #2 only. All changes of batch #0 are lost forever!
    end
```

**Comment by Mimetis** [comment] 2020-10-14 07:19
Thank @gentledepp !

Do you have a sample repro to share ? I'm really curious how you finally manage to make this bug happening :)

**Comment by gentledepp** [comment] 2020-10-14 08:07
Sure - there are two integration tests in `HttpServerTests` right at the bottom.

If you just comment out my null-check in the `WebServerOrchestrator` starting at line `504`
```diff
-            // ensure that the blientBatchInfo is still available in the session - it **must** only be null when the batchIndex is 0!!
-            if (sessionCache.ClientBatchInfo == null && httpMessage.BatchIndex != 0)
-                throw new SyncException("Session loss: No batchPartInfo could found for the current sessionId. It seems the session was lost. Please try again.");

```   
then you will see the issue in the test `WithBatchingEnabled_WhenSessionIsLostDuringApplyChanges_ChangesAreNotLost` right away, because it will break in line `1570`

```csharp
            try
                {
                    var s = await agent.SynchronizeAsync();

                    // Query number of **actually** transmitted rows!
                    // **without the null check in WebServerOrchestrator, the following 3 asserts will succeed**
                    // **meaning the client will assume it send all the local changes successfully**
                    Assert.Equal(rowsToSend, s.TotalChangesUploaded);
                    Assert.Equal(0, s.TotalChangesDownloaded);
                    Assert.Equal(0, s.TotalResolvedConflicts);

                    using (var serverDbCtx = new AdventureWorksContext(this.Server))
                    {
                        var serverCount = serverDbCtx.Product.Count(p => p.ProductNumber.Contains($"{productNumber}_"));
                        // **but it will break here, as only ~600 of the total 1000 rows are actually inserted at the server side** 
                        Assert.Equal(rowsToSend, serverCount);
                    }

                }
                catch (SyncException x)
                {
                    exception = x;
                }
```

**Comment by Mimetis** [comment] 2020-10-14 08:25
Yep, I see it now, but not in the message before

**Comment by gentledepp** [comment] 2020-10-14 08:33
Ok... too bad that it is not yet natively supported by Github. The wiki of Visual Studio DevOps does support it out-of-the-box.
I installed a chrome plugin that does the trick here: https://chrome.google.com/webstore/detail/github-%20-mermaid/goiiopgdnkogdbjmncgedmgpoajilohe

Take a look at [mermaidjs](https://mermaid-js.github.io/mermaid/#/). it allows you to define charts in markdown syntax
There is even a [live-editor for mermaidjs](https://mermaid-js.github.io/mermaid-live-editor//#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpXG4gIEIgLS0-IEN7TGV0IG1lIHRoaW5rfVxuICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICBDIC0tPnxUd298IEVbaVBob25lXVxuICBDIC0tPnxUaHJlZXwgRltmYTpmYS1jYXIgQ2FyXVxuXHRcdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

**Closed** 2021-01-09 14:38 UTC
