### ISSUE TITLE
Deprovision 

### ISSUE THREAD

**Issue by PardeepBhandari** [Mimetis/Dotmim.Sync#428] opened 2021-02-05 11:15 UTC
Hi
 I am using sql server for sever and Client .
My Client database was a blank database and all the data was in server 7 tables are there .
I manage to sync child database with server using code
```vb
 Dim SyncObj As New SyncDB
        Dim serverConnectionString As String, clientConnectionString As String, TempString As String
        Dim Messages As String = ""
        lblMessage.Text = ""

        Dim tables = New String() {"Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData"}
        Dim ServerIP As String = TxtRemoteServer.Text
        Dim DBName As String = TxtRemoteDB.Text
        Dim DBUserID As String = TxtRemoteUserID.Text
        Dim DBPassword As String = TxtRemotePassword.Text

        Try
            serverConnectionString = $"Data Source={ TxtRemoteServer.Text};timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtRemoteDB.Text} ;Persist Security Info=True;User ID={TxtRemoteUserID.Text};Password={TxtRemotePassword.Text} ;"
            clientConnectionString = $"Data Source={ TxtClientServer.Text }; timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtClientDB.Text} ; Persist Security Info=True; User ID={TxtClientUserID.Text}; Password={TxtClientPassword.Text} ;"

            Dim serverProvider As SqlSyncProvider = New SqlSyncProvider(serverConnectionString)
            Dim syncoptions = New SyncOptions() With {.BatchSize = Val(TxtBuffer.Text)}

            Dim Setup = New SyncSetup(tables)
            Setup.StoredProceduresPrefix = "all"
            Setup.StoredProceduresSuffix = ""

            Dim clientProvider As SqlSyncProvider = New SqlSyncProvider(clientConnectionString)
            Dim agent As SyncAgent = New SyncAgent(clientProvider, serverProvider, syncoptions, Setup, "All")

            Dim syncContext As Object

            If OptNormal.Checked Then
                syncContext = Await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Normal)
            ElseIf OptReinitialize.Checked Then
                syncContext = Await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Reinitialize)
            ElseIf OptReinitializeWithUpload.Checked Then
                syncContext = Await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.ReinitializeWithUpload)
            Else
                syncContext = Await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Normal)
            End If

            TxtMessage.Text = syncContext.ToString()

        Catch ex As Exception
            Dim I As Integer
            I = 0
            lblMessage.Text = ex.InnerException.Message
        End Try
```
It is ok and running fine.
but after that i want to deprovision so that i can alter my database adding column removing column.
I am using following code for deprovision.

```vb

 Dim SyncObj As New SyncDB
        Dim serverConnectionString As String, clientConnectionString As String, TempString As String
        Dim Messages As String = ""
        lblMessage.Text = ""
        '
        Dim tables = New String() {"Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData"}


        clientConnectionString = $"Data Source={ TxtClientServer.Text }; timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtClientDB.Text} ; Persist Security Info=True; User ID={TxtClientUserID.Text}; Password={TxtClientPassword.Text} ;"

        Dim clientProvider As SqlSyncProvider = New SqlSyncProvider(clientConnectionString)
        Dim Setup = New SyncSetup(tables)
        Dim syncoptions = New SyncOptions()

        ' Create a local orchestrator used to Deprovision everything
        Dim LocalOrchestrator = New LocalOrchestrator(clientProvider, syncoptions, Setup)

        ' Get the local scope
        Dim clientScope = Await LocalOrchestrator.GetClientScopeAsync()


		' This Line Not Work
        Await LocalOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures & SyncProvision.Triggers & SyncProvision.TrackingTable & SyncProvision.Table)
		
		' This Line Remove TrackingTable
         Await LocalOrchestrator.DeprovisionAsync(SyncProvision.TrackingTable)
		 
		' This Line Not Work
         Await LocalOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures)

		' This Line Remove Triggers
		Await LocalOrchestrator.DeprovisionAsync(SyncProvision.Triggers)
		
		' This Line Remove Table But I Don't Want
         Await LocalOrchestrator.DeprovisionAsync(SyncProvision.Table)
		 
        ' affect good values

        clientScope.Setup = Nothing
        clientScope.Schema = Nothing

        'save the local scope DeprovisionAsync
        'Await LocalOrchestrator.WriteClientScopeAsync(clientScope)
```

I am not able to remove StoredProcedures with  Await LocalOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures)
What If client database already have same table structure and other point if client table have same  structure and data.
is syncing possible or i need to drop all the table or i should clear all the data.

**Comment by Mimetis** [comment] 2021-02-08 08:57
What kind of errors do you get when you tried to `DeprovisionAsync` ?

By the way, you are not allowed to deprovision tables.
This is by design. Once tables are generated `DMS` will never drop them, even if you specify `SyncProvision.Table` in the `DeprovisionAsync` method.

And finally, your call to ``Deprovision` seems wrong.
Should be (in C# at least)

``` cs
await localOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable);
```
And not
``` cs
await localOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures & SyncProvision.Triggers & SyncProvision.TrackingTable);
```

Notice the `|` instead of `&`

Let me know if it's resolving your issue !

**Comment by PardeepBhandari** [comment] 2021-02-08 17:27
Hi

I use code ```vb
 Dim SyncObj As New SyncDB
        Dim serverConnectionString As String, clientConnectionString As String, TempString As String
        Dim Messages As String = ""
        lblMessage.Text = ""
        '
        Dim tables = New String() {"Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData"}


        clientConnectionString = $"Data Source={ TxtClientServer.Text }; timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtClientDB.Text} ; Persist Security Info=True; User ID={TxtClientUserID.Text}; Password={TxtClientPassword.Text} ;"

        Dim clientProvider As SqlSyncProvider = New SqlSyncProvider(clientConnectionString)
        Dim Setup = New SyncSetup(tables)
        Dim syncoptions = New SyncOptions()

        ' Create a local orchestrator used to Deprovision everything
        Dim LocalOrchestrator = New LocalOrchestrator(clientProvider, syncoptions, Setup)

        ' Get the local scope
        Dim clientScope = Await LocalOrchestrator.GetClientScopeAsync()

        ' Deprovision everything+

        Await LocalOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures Or SyncProvision.Triggers Or SyncProvision.TrackingTable)

        ' affect good values

        clientScope.Setup = Nothing
        clientScope.Schema = Nothing

        'save the local scope
        'Await LocalOrchestrator.WriteClientScopeAsync(clientScope)
```

**Comment by Mimetis** [comment] 2021-02-08 17:52
Your setup should be the SAME as the one you've used when your made a previous sync
It contains all the metadata that `DMS` needs to deprovision (like prefix and suffix for instance)

And no, you don't need to drop existing tables. DMS is able to work with already existing client tables, if they have the same structure as the servef

**Closed** 2021-02-21 20:58 UTC
