### ISSUE TITLE
Sync fails with duplicate key constraint failue

### ISSUE THREAD

**Issue by Craige** [Mimetis/Dotmim.Sync#962] opened 2023-02-09 04:51 UTC
Syncing from Sqlite to MySQL. First sync syncs to from the  server to the client. Subsequent sync (to sync lo local change to the remote) fails with:

```
[InternalApplyThenGetChangesAsync]..[InternalApplyThenGetChangesAsync]..[InternalSaveScopeInfoClientAsync]..Duplicate entry '3ea49ef3-02c8-4cd0-af39-7acffab1338f-v1-YRV8q709t1f3m4tvB/5mP...' for key 'PRIMARY' (Dotmim.Sync.SyncException)
   at Dotmim.Sync.RemoteOrchestrator.InternalApplyThenGetChangesAsync(ScopeInfoClient cScopeInfoClient, ScopeInfo cScopeInfo, SyncContext context, ClientSyncChanges clientChanges, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress`1 progress)
[...]
```
It does appear before this that the client change is synced to the server, but something is going wrong here. This is with a minimal stock sync setup:

```
public class Foo
{
    public MariaDBSyncProvider ServerProvider { get; set; }
    public SqliteSyncProvider ClientProvider { get; set; }
    public SyncSetup Setup { get; set; }
    public SyncAgent Agent { get; set; }

    public Foo()
    {       
        ServerProvider = new MariaDBSyncProvider("Data Source=localhost,3306;Initial Catalog=project;User ID=user;Password=password");
        var path = ""; // redacted for simplicity
        ClientProvider = new SqliteSyncProvider(path);

        Setup = new SyncSetup("Table1", "Table2");

        Agent = new SyncAgent(ClientProvider, ServerProvider);
    }
    public async Task onEvent()
    {
        // Persist local changes...

        //...

        // Sync to remote...
        var result = await Agent.SynchronizeAsync("v1", Setup, SyncType.ReinitializeWithUpload);
        Console.WriteLine(result);
    }
}

```
Using:
```
      <PackageReference Include="Dotmim.Sync.MariaDB" Version="0.9.8" />
      <PackageReference Include="Dotmim.Sync.Sqlite" Version="0.9.8" />
```

**Comment by Mimetis** [comment] 2023-02-09 16:27
Hey @Craige 
Do you have a sample MariaDB sql script to recreate your server database ? (just tables Table1 and Table2) 
I will be able to reproduce your error and help you fix it

**Comment by Craige** [comment] 2023-02-10 00:39
Let me put together a quick console app demonstrating the failure and I'll get back to you.

**Comment by Craige** [comment] 2023-02-11 02:05
The console app I just setup synchronized correctly with a similar setup, so there must be something about how I'm using it in the Maui app that I originally tried to configure.

I'm going to continue digging and see if I can figure out the difference.

As for the error itself, I think it's trying to create a new client record on the server with every synchronization.

**Comment by Craige** [comment] 2023-02-19 05:04
So the problem seems to be with this line:

https://github.com/Mimetis/Dotmim.Sync/blob/master/Projects/Dotmim.Sync.MySql/Builders/MySqlScopeInfoBuilder.cs#L662

The GUID is being mangled when run through the parameter converter [here](https://github.com/Mimetis/Dotmim.Sync/blob/master/Projects/Dotmim.Sync.Core/Orchestrators/Scopes/BaseOrchestrator.ScopeInfos.cs#L444) during initial negotiation. This tells the Orchestrator that the scope_info_client doesn't exist (because it's being looked as a mangled guid), and then it subsequently tries to create record with the real guid, but it already exists.

The solution here is to consistently use the `DbType.Guid` in the builder classes for guids. Sometimes they are typed as Guid, sometimes they are typed as String.

And I have no idea why this works sometimes and not others, but correcting these types seems to fix the problem for me.

**Comment by maniish** [comment] 2023-02-22 06:58
I have temporary reverted to previous beta version to work. Please update on this.

**Comment by Craige** [comment] 2023-02-24 16:08
I'm not quite sure what you mean.

**Comment by maniish** [comment] 2023-02-27 08:41
Just wanted to know once it is fixed.

**Comment by symbiogenesis** [comment] 2023-03-17 04:06
Since this was likely fixed here, you could pull in the code from master and it would work.

https://github.com/Mimetis/Dotmim.Sync/pull/969

Hopefully a minor version will make it to nuget soon.

**Comment by maniish** [comment] 2023-03-23 07:10
Hi Edward,

Can you please let me know if this fix is incorporated in any version which
I can get using nuget?

Kind Regards,
Manish Pansiniya
Founder & Director
IntelliPro Solutions Pvt Ltd
p: 91 79 40095674  m: 91 9898912298
w: www.iprospl.com  e: ***@***.***
<https://www.facebook.com/IntelliPro>   <https://twitter.com/iprospl>
<https://www.linkedin.com/company/intellipro-solutions-pvt-ltd>

**Comment by MaTToX3** [comment] 2023-04-14 09:49
It's not, last version was on 30th of January 2023.

**Comment by maniish** [comment] 2023-04-14 09:52
Are we going to integrate in the new version soon? Can somebody answer?

**Comment by Mimetis** [comment] 2023-04-14 10:20
next version will be publish early next month I think

**Comment by MaTToX3** [comment] 2023-04-14 11:24
Any plans for 1.0.0?

**Comment by symbiogenesis** [comment] 2023-05-05 17:40
Would be interested to see a point release with this fix.

**Closed** 2023-07-19 07:50 UTC
