### ISSUE TITLE
DotMimSync Scalability/performance issue - SQL Change Tracking Retention Period???

### ISSUE THREAD

**Issue by govdevteam** [Mimetis/Dotmim.Sync#751] opened 2022-07-01 04:57 UTC
Our team recently ran across an interesting issue involving failed synchronizations involving DotMimSync in higher utilization environments. While we do not necessarily believe that DotMimSync is to blame, we did observe that some of the MS SQL Server Change Tracking settings, including the "Retention Period", may have contributed to these performance issues.

In an effort to provide context, here is some background information for reference:

1) We utilize MS SQL Server 2016/2019 in our DEV/TEST/DEMO/TRAINING/PROD environments
2) Our client software apps utilize SQLITE
3) We utilize DotMimSync to synchronize data between the client-side SQLITE datastore and the SQL Server database environment that drives our web portal

Over the past month, we followed our standard software release deployment process and subsequently deployed our latest software release to DEV, then to TEST, then to DEMO, and then to TRAINING environments without any issue. However, after we deployed the software release to PROD, we started noticing that a small number of users (~3% of all PROD users) were not able to complete the data synchronization process while the remaining 97% of users experienced no issues. The only difference between the PROD environment and our other environments is the number of end users (5-100 in our non-Production environments vs. ~2,000 - 3,000 users in our PROD environment).

When analyzing server performance, we observed significant (maxed out) resource utilization on our SQL Server instance and discovered that we had initially configured the "Retention Period" for Change Tracking to "14 days" based on other information posted in the DotMimSync project. However, when we changed the "Retention Period" from "14 days" to "2 days", all of the sync issues went away and our PROD environment started working as expected just like our other environments.

Based on this issue, we would like to know whether anyone else has experienced performance issues using MS SQL Server, SQLITE, and DotMimSync with a Retention Period of 14 days. Furthermore, we would like to know if anyone can think of any potential DotMimSync issues that we could experience if we maintain a Retention Period of 2 days rather than 14 days. For example, if we have a user that completes a login, does not log out (e.g. data synchronization doesn't take place), and then accesses the system 7 days later, would we necessarily lose of the user's unsynchronized data since it is outside of the retention period? Finally, does anyone have any recommendations with regards to an appropriate "Retention Period" for DotMimSync users?

Any input and/or feedback would be greatly appreciated.

**Comment by VagueGit** [comment] 2022-07-01 05:25
Chipping in possibly pointlessly ... we have a similar number of users with DMS on SQL Server 2019 and SQLite. My contribution is probably pointless because our customers are small companies and each company has it's own database on our SQL Server. Each company has 1-20 users.

We extended the retention period on SQL Server from 14 days to 2 months without noticeable performance issues arising. We extended the retention period because most of our customers shut down for a month or so over xmas/new year so there was risk of data loss if data was not synced before the break.

I would have thought the performance impact on the server of varying the retention period would be similar whether there were one database or many, but I'm usually wrong about most things.

**Comment by govdevteam** [comment] 2022-07-02 21:18
> Chipping in possibly pointlessly ... we have a similar number of users with DMS on SQL Server 2019 and SQLite. My contribution is probably pointless because our customers are small companies and each company has it's own database on our SQL Server. Each company has 1-20 users.
> 
> We extended the retention period on SQL Server from 14 days to 2 months without noticeable performance issues arising. We extended the retention period because most of our customers shut down for a month or so over xmas/new year so there was risk of data loss if data was not synced before the break.
> 
> I would have thought the performance impact on the server of varying the retention period would be similar whether there were one database or many, but I'm usually wrong about most things.

**Comment by govdevteam** [comment] 2022-07-02 21:33
@VagueGit Thank you for your reply. On one hand, I am surprised that you have not experienced any issue even after expanding the retention period from 14 days to 2 months. On the other hand, it seems like you have a bunch of small databases (1 for each company) whereas we have one large database with each customer configured as a "tenant" organization. In theory, it should not matter but in practice I'm certain that our enviornment would crash completely if we set the retention period to 2 months.

I do have one more question for you, though. I recently noticed that, when synchronizing the SQLite data store using DotMimSync, we have three files:

1) SQLite datastore
2) Shared Memory (SHM) file
3) Write Ahead Log (WAL) file

Previously, when closing our application, the SHM & WAL files would "disappear" upon completing a checkpoint (i.e. after the application is closed). However, I now notice that the SHM & WAL files persist even after the application is closed. Have you experienced this using DotMimSync and SQLite?

**Comment by VagueGit** [comment] 2022-07-02 21:57
We don't use Write Ahead Logging. I know it is more performant but when we tried it, users complained that devices within a company were not being kept uptodate with the latest changes.

I'm not an expert with SQLite (nor much else for that matter) but my understanding is the WAL file persists until a checkpoint is reached. It would not necessarily be deleted when they app closed if a checkpoint has not been reached and changes exist in the WAL waiting to be persisted..

**Comment by Mimetis** [comment] 2022-07-04 10:09
> Previously, when closing our application, the SHM & WAL files would "disappear" upon completing a checkpoint (i.e. after the application is closed). However, I now notice that the SHM & WAL files persist even after the application is closed. Have you experienced this using DotMimSync and SQLite?

Pooled connections may be the cause (look https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/breaking-changes#mitigations-3 & https://github.com/dotnet/efcore/issues/26580)

You need to clear the connection pools before closing your application

``` cs
SqliteConnection.ClearAllPools();
```

**Closed** 2022-08-10 20:56 UTC

**Comment by MarkLFT** [comment] 2023-06-05 08:09
@govdevteam We are looking at using this in a multi-tenant environment.  We have a mix of some tenants have their own database, whilst others shared a database with a tenantId field.  Can you tell me how you achieved your multi-tenancy using this lib.  Thanks
