### ISSUE TITLE
[enhancement] self referencing table

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#39] opened 2018-01-15 18:36 UTC
Hello,
I know, this is acutally not supported, but IMO this should be part of the solution:
Sample: Table "Folders" with fields Id[guid] and ParentId[guid] and FolderName[string]

Actually I need to setup this without ForeignKey, as otherwise Sync stopps.
It's not a showstopper, but if there is a solution to Support this Scenario, this would be great.

thx
reinhold

**Comment by Mimetis** [comment] 2018-09-08 17:13
The problem is the order of the inserts from your server in your clients databases.
  
If I take your example, you don't have any guarantee that that a parent row will be inserted *before* its child rows, in the destination database.

Even if we order the primary keys, maybe your key is a `varchar(10)`, your parent folder is called **FOO** and one of its child is called **BAR**

In this particular case, the child row **BAR**  will be sync in first, before the parent row **FOO** and the foreign key constraint will fail.

That's why, until we have a strong solution, self referencing foreign keys are disabled.

**Closed by Mimetis** 2018-09-08 17:13 UTC
