### ISSUE TITLE
data downloaded on first attempt goes mising after second sync in some sqlite tables.

### ISSUE THREAD

**Issue by sojan1** [Mimetis/Dotmim.Sync#1107] opened 2023-09-26 00:56 UTC
i have filtered with MASTER to download on first attempt. and it downloaded everything. 
then i used the second filter 'Demo 2a' to download another set of records. 

After successfully synching the data, for 'Demo 2a', data with the first filter goes missing in some tables.

 
**first sync**
            var parameters2 = new SyncParameters
                {
                    { "CLNT_ID","D1" },
                    { "PROJ_ID","MASTER" }
                };

**second sync**
            var parameters2 = new SyncParameters
                {
                    { "CLNT_ID","D1" },
                    { "PROJ_ID","Demo 2a" }
                };

Provisioning Code- 
 var result = await remoteOrchestrator.ProvisionAsync(txtScopeName.Text, setup, SyncProvision.NotSet, false, null, null, default, progress);

```
Client Code -    
 var serverProvider = new SqlSyncChangeTrackingProvider("Data Source=SERVERMACHINE\\SQLEXPRESS01; Initial Catalog=CORE2; Integrated Security=true;Trusted_Connection=true;TrustServerCertificate=True;MultipleActiveResultSets=False;");


            SqliteSyncProvider clientProvider = new SqliteSyncProvider(@"Data Source=C:\\Users\\sojan.GEROC\\Documents\\Projects\\Dotmim.Sync-master\\SyncInstaller\\CoreDatabase.db");
            // Set the web server Options
            var options = new SyncOptions
            {
                BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDirectory(), "client")
            };
            //options.TransactionMode = TransactionMode.AllOrNothing;
            var agent = new SyncAgent(clientProvider, serverProvider, options);
            agent.SessionStateChanged += Agent_SessionStateChanged;
            //agent.LocalOrchestrator.on
            var progress = new SynchronousProgress<ProgressArgs>(
                  pa => Console.WriteLine($"{pa.ProgressPercentage:p}\t {pa.Message}"));
            //progress.ProgressChanged += Progress_ProgressChanged;

            var parameters2 = new SyncParameters
                {
                   { "CLNT_ID","D1" },
                   { "PROJ_ID","MASTER" }
                };


            //  var s1 = await agent.SynchronizeAsync("v0", SyncType.Normal, parameters, progress);
            var s2 = await agent.SynchronizeAsync("v0", SyncType.Normal, parameters2, progress);

            Console.WriteLine(s2);
```

**Comment by sojan1** [comment] 2023-09-26 05:43
Hi please someone help me. 
There is only 3 provisioned tables in sql server db. 

It syncs both filters on 'project' table and '_desx' table  but first record disappears from '_desx' table after the second sync
But project table have both records. 

https://github.com/sojan1/SyncInstaller

**Comment by symbiogenesis** [comment] 2023-09-26 06:29
I have noticed weird Sqlite issues with the latest versions that were fixed by rolling back to 0.9.6

Some change between 0.9.6 and 0.9.7 caused a problem for me. Try rolling back.

But hopefully your test case will help get to the root cause of it.

**Comment by sojan1** [comment] 2023-09-26 07:14
Thanks i will try that.

**Comment by sojan1** [comment] 2023-09-26 21:12
there was a typo error with GetDefaultUserBatchDiretory with the older version 0.9.6 i changed it to match the name in the that version.

then i am getting a DBNull Exception.
![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/0d491685-30c5-47d2-a128-22024e397b17)

**Comment by sojan1** [comment] 2023-09-26 21:49
Hi @Mimetis  Please kindly help, Thanks .....

**Comment by sojan1** [comment] 2023-09-27 00:46
This has nothing to do with DMS. 
There were cascading applied on my sqlite tables i removed the cascading on client sqlite and it it syncs well. 

@symbiogenesis  Thank you.

**Closed** 2023-09-27 12:14 UTC

**Comment by Mimetis** [comment] 2023-09-27 22:28
Disable Cascade
