### ISSUE TITLE
MessagePack serialiser HttpMessageEnsureSchemaResponse exception

### ISSUE THREAD

**Issue by gb0o** [Mimetis/Dotmim.Sync#325] opened 2020-09-02 00:15 UTC
Hi @Mimetis 

I've been testing the MessagePack serialiser using the example implementation and get an exception when attempting to seralise HttpMessageEnsureSchemaResponse on the client side.

```
2020-09-01 22:55:50 +10:00 [INF] ScopeLoaded:	10:55:50 PM.137	 [main] [radio] [Version ] Last sync: Last sync duration:0:0:0.0 
2020-09-01 22:56:05 +10:00 [ERR] SyncException { TypeName: "MessagePackSerializationException", SyncStage: None, Number: 0, DataSource: null, InitialCatalog: null, Side: ClientSide, Message: "Failed to serialize Dotmim.Sync.Web.Client.HttpMessageEnsureSchemaResponse value.", Data: [], InnerException: null, TargetSite: Void MoveNext(), StackTrace: "   at Dotmim.Sync.Web.Client.HttpRequestHandler.<HandleSyncError>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Dotmim.Sync.Web.Client.HttpRequestHandler.<ProcessRequestAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.<EnsureSchemaAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Radio.Sync.Services.SyncService.<SynchronizeAsync>d__11.MoveNext() in C:\work\radio-sync\Radio.Sync.Services\SyncService.cs:line 78", HelpLink: null, Source: "Dotmim.Sync.Web.Client", HResult: -2146233088 }
2020-09-01 22:56:05 +10:00 [ERR] Failed to serialize Dotmim.Sync.Web.Client.HttpMessageEnsureSchemaResponse value.
```

I implemented ISerializerFactory and ISerializer<T> interfaces for a MessagePack serialiser/deserialiser as follows:

```
﻿using System.IO;
using System.Threading.Tasks;
using Dotmim.Sync.Serialization;
using MessagePack;
using MessagePack.Resolvers;

 namespace Radio.Sync.API.Serializer
{
    public class CustomMessagePackSerializerFactory : ISerializerFactory
    {
        public string Key => "mpack";

        public ISerializer<T> GetSerializer<T>()
        {
            return new CustomMessagePackSerializer<T>();
        }
    }

    public class CustomMessagePackSerializer<T> : ISerializer<T>
    {
        private readonly MessagePackSerializerOptions _options;

        public CustomMessagePackSerializer()
        {
            _options = MessagePackSerializerOptions.Standard.WithResolver(ContractlessStandardResolver.Instance);
        }

        public async Task<T> DeserializeAsync(Stream ms)
        {
            var val = await MessagePackSerializer.DeserializeAsync<T>(ms, _options);
            return val;
        }

        public async Task<byte[]> SerializeAsync(T obj)
        {
            using (var ms = new MemoryStream())
            {
                await MessagePackSerializer.SerializeAsync(ms, obj, _options);
                return ms.ToArray();
            }
        }
    }
}
```

On the server side I added the factory to WebServerOptions
```
	var options = new WebServerOptions
	{
	    ServerCacheSlidingExpiration = TimeSpan.FromSeconds(webServerOptions.ServerCacheSlidingExpirationSecs),
	    ClientCacheSlidingExpiration = TimeSpan.FromSeconds(webServerOptions.ClientCacheSlidingExpirationSecs),
	};
	options.Serializers.Add(new CustomMessagePackSerializerFactory());
```

On the client side I added to the WebClientOrchestrator
```
	return new WebClientOrchestrator($"{_endPoint}/sync")
	{
	    Setup = _syncSetup,
	    Options = _syncOptions,
	    HttpClient = {Timeout = TimeSpan.FromMinutes(60)},
	    SerializerFactory = new CustomMessagePackSerializerFactory()
	};
```

Could it be objects contained in HttpMessageEnsureSchemaResponse are not agreeing to be serialised? Maybe MessagePack requires special annotations `Key` etc rather than `DataContract` and `DataMember`?

Regards,
Guy

**Comment by Mimetis** [comment] 2020-09-02 20:23
Thanks, I will make more tests on this
Will update as soon as possible

**Comment by gb0o** [comment] 2020-09-03 23:43
The class `SetupFilter` has two properties that both have `Order = 5` in the `DataMember` attribute. Probably harmless as the every tagged property will serialised with an order decided explicitly or not, just not defined here correctly. 

Guy

```
    /// <summary>
    /// Design a filter clause on Dmtable
    /// </summary>
    [DataContract(Name = "sf"), Serializable]
    public class SetupFilter : SyncNamedItem<SetupFilter>
    {

       ...

        /// <summary>
        /// Gets the parameters list, used as input in the stored procedure
        /// </summary>
        [DataMember(Name = "p", IsRequired = false, EmitDefaultValue = false, Order = 5)]
        public List<SetupFilterParameter> Parameters { get; } = new List<SetupFilterParameter>();

        /// <summary>
        /// Side where filters list
        /// </summary>
        [DataMember(Name = "w", IsRequired = false, EmitDefaultValue = false, Order = 5)]
        public List<SetupFilterWhere> Wheres { get; } = new List<SetupFilterWhere>();
```

**Comment by gb0o** [comment] 2020-09-04 09:37
I just read [comments](https://github.com/Mimetis/Dotmim.Sync/issues/255#issuecomment-635277005) from @gentledepp that the MessagePack `ContractlessStandardResolver` in the [SerializerConverter](https://dotmimsync.readthedocs.io/SerializerConverter.html) implementation won't work for native .NET.  Seems MessagePack attributes ([Key(0)] are required. Unfortunately I'm using a WPF client but it doesn't matter too much if I can't use MessagePack because I'm more than happy with the performance improvement using the build-in serialisers.

**Comment by Mimetis** [comment] 2020-09-04 09:48
It should work with WPF, so I'll fix it as soon as possible
It could be the `Order` that causes the issue.
I've added the `Order` attribute because of `MessagePack` actually, so definitively needs to see if the bug is coming from that !

**Comment by Mimetis** [comment] 2020-09-07 11:31
@gboo The fix has been applied on the master branch
I've created tests as well to be sure we won't have again this kind of issues

**Closed by Mimetis** 2020-09-07 11:31 UTC
Labels: bug

**Comment by gb0o** [comment] 2020-09-08 23:53
@Mimetis confirmed MessagePack serialiser/deserialiser is working in my WPF project. Thankyou for fixing. Sync is now a little faster: for my heavy sync it was 0:11:46.745 and is now 0:10:29.596  (h:mm:ss). 

Were you able to pin point the cause of the exception? Was it the `Order` attribute duplicate, missing ctor() etc?

Guy

**Comment by Mimetis** [comment] 2020-09-09 11:37
Indeed @gb0o, the `Order` property was one of the problems. The other problem was coming from a constructor that should be empty (and existing) to allow deserialization.

If you are using a WPF application, the last commit on the [MariaDB](https://github.com/Mimetis/Dotmim.Sync/tree/MariaDB)  branch has added some new perf improvement and some bug fixes around *UI Freeze* that can happen with the previous version.

You should give it a try and see if the UI is freezing less than usual

**Comment by gb0o** [comment] 2020-09-09 12:38
I guess MessagePack requires empty constructors to invoke and discovery properties using it's so called contractless resolver. 

Anything that improves UI performance is good for my WPF app. I noticed you kick off a few more threads with `await Task.Run(async () => {...})`.  I already wrap the entire sync process within a thread so not sure it will make a difference to the UI. 

I'll wait until the [MariaDB](https://github.com/Mimetis/Dotmim.Sync/tree/MariaDB) is merged then I can test but definitely interested in further performance improvments that you may have made.

**Comment by vunder** [comment] 2020-09-09 13:33
@Mimetis  I agree with @gb0o 
Such wrap does not give any profit. The result would be th same, but you're adding additional memory traffic to create Task wrappers and time that spend on context switching. The problem is usually is because of mixing async model and blocking model (by `GetResult`)

**Comment by Mimetis** [comment] 2020-09-09 13:43
There is no more `GetResult` in the code, thanks to the `IAsyncEnumerable` and the `Microsoft.Bcl` package for `.Net Standard 2.0` compatibilty.

Overall, there is only two `Task.Run` in the whole library, and each one is executed depending your option settings (so you will allways executing only one of them)

Then, we are using `ConfigureAwait(false)` by default, so there is not too much context switching, I assume.

Depending on the numbers of rows, the freeze can be really long, especially if you're not using the **batch** mode.

You should give it a try and see if you have a big decrease of performances

**Comment by vunder** [comment] 2020-09-09 13:51
`Task.Run` force to run action code within the new thread. Even if `Thread.CurrenctThread.ManagerThreadId` would be the same before and within `Task.Run` action (threads could be reused), there would be context switch since execution context is different.
Anyway. Since my sample for batches is still valid, I can help you with testing

**Comment by Mimetis** [comment] 2020-09-09 14:01
If you get the `MariaDB` branch, you will see that I've added a blue bar to the left of the WPF UI to see UI thread blocking
It helped me a lot to figure out where the UI freezes came from

**Comment by Mimetis** [comment] 2020-09-10 06:38
`MariaDB` branch merged into `master` :)
