### ISSUE TITLE
SyncException InvalidOperationException:  Can't create a SqlRecord based on the rows we have: Value was either too large or too small for a Decimal.

### ISSUE THREAD

**Issue by menitamoses** [Mimetis/Dotmim.Sync#591] opened 2021-08-17 21:29 UTC
I have a download only sync operation from Server to server client DBs. One of the DB sync failed with this error

**Encountered SyncException InvalidOperationException Can't create a SqlRecord based on the rows we have: Value was either too large or too small for a Decimal.**

I encountered something when using MS Sync..here is the link to support issue
https://support.microsoft.com/en-us/topic/fix-system-overflowexception-value-was-either-too-large-or-too-small-error-message-when-you-perform-data-synchronization-by-using-sync-framework-2-1-76b52681-1025-b124-f316-484319be8aed

Is this similar problem in Dotmim? If it is, can we please have a patch with a fix?

Thanks in advance

**Comment by Mimetis** [comment] 2021-08-17 22:23
I dont know, you should try I guess.
If you encounter the same problem, plz provide a sample to help me repro the issue

**Comment by menitamoses** [comment] 2021-08-17 22:37
I am using DotmimSyn currently for all sync jobs. However, I was using MS Sync before than and I recall running into similar issue there. I included the link for the fix in MS Sync.

I am hoping you can locate the code in DotmimSync lib and provide a similar fix. I cant provide code to reproduce it since the issue happened with DotmimSync library on a sync cycle

**Comment by Mimetis** [comment] 2021-08-17 22:45
Dotmim.Sync is completely different from MS Sync Framework.
I will close this issue until it actually happens :)
Let me know if it's making sense

**Comment by menitamoses** [comment] 2021-08-17 22:58
This is happening on DotmimSync. I mentioned MS Sync just to give you a reference for the fix. 
The above exception is happening in DotmimSync

**Comment by Mimetis** [comment] 2021-08-17 23:11
The code from the `SqlSyncProvider` is:

``` cs
        public override DbCommand GetLocalTimestampCommand(DbConnection connection, DbTransaction transaction)
        {
            // UPDATE Nov 2019 : We don't use min_active_rowversion anymore, since we are in a transaction
            // and we still need the last row version "during the transaction", so check back to @@DBTS


            var command = connection.CreateCommand();
            command.Transaction = transaction;


            command.CommandText = "SELECT CONVERT(bigint, @@DBTS) as lastTimestamp";


            DbParameter p = command.CreateParameter();
            p.ParameterName = "@sync_new_timestamp";
            p.DbType = DbType.Int64;
            p.Direction = ParameterDirection.Output;
            command.Parameters.Add(p);


            return command;
        }
```

And the caller from `BaseOrchestrator` is:

``` cs
        internal async Task<long> InternalGetLocalTimestampAsync(SyncContext context,
                             DbConnection connection, DbTransaction transaction,
                             CancellationToken cancellationToken, IProgress<ProgressArgs> progress = null)
        {
            var scopeBuilder = this.GetScopeBuilder(this.Options.ScopeInfoTableName);


            // we don't care about DbScopeType. That's why we are using a random value DbScopeType.Client...
            var command = scopeBuilder.GetCommandAsync(DbScopeCommandType.GetLocalTimestamp, DbScopeType.Client, connection, transaction);


            if (command == null)
                return 0L;


            var action = new LocalTimestampLoadingArgs(context, command, connection, transaction);


            await this.InterceptAsync(action, cancellationToken).ConfigureAwait(false);


            if (action.Cancel || action.Command == null)
                return 0L;


            long result = Convert.ToInt64(await action.Command.ExecuteScalarAsync().ConfigureAwait(false));


            var loadedArgs = new LocalTimestampLoadedArgs(context, result, connection, transaction);
            await this.InterceptAsync(loadedArgs, cancellationToken).ConfigureAwait(false);


            return loadedArgs.LocalTimestamp;
        }
```

So, are you sure we have an `System.OverflowException` exception ?

**Comment by menitamoses** [comment] 2021-08-17 23:24
Thank you for the code snippet. Looks like you are converting timestamp value to BIGINT in GetLocalTimestampCommand correctly. Do you suppose there may be some areas in code where that conversion may not be happening?
I have 4 clients syncing to my server and only 1 ran in to this Exception

**Comment by Mimetis** [comment] 2021-08-17 23:26
dont think so

**Comment by Mimetis** [comment] 2021-08-18 10:04
Can you share the exception raised by `DMS` ?

**Comment by menitamoses** [comment] 2021-08-18 16:15
I have try()..catch()  around my Dotmim sync operation and the exception was caught
 catch (SyncException syncExp)
                {
                    Logger.Sync.Warn(
                        $"Encountered SyncException {syncExp.TypeName} {syncExp.Message}");
}
The exception type is **InvalidOperationException** ...so I am assuming DMS is bubbling up a SQL exception.

I am out of office for next 4 days. I will touch base with you next week. Thanks so much for looking in to this.

**Comment by Mimetis** [comment] 2021-09-07 08:05
Not able to reproduce this error.
Can you share a code sample that reproduces your issue ?

**Comment by menitamoses** [comment] 2021-09-08 00:09
This is the try/catch that produced the error. I cant replicate the issue in a predictable manner. I dont even know which table/col would throw that error. According to your code sample you are converting timestamp to BigInt, so I am not sure what/where the source of this problem might be
try
                {
                    var serverProvider = new SqlSyncProvider(Publisher.ConnectionString);
                    var clientProvider = new SqlSyncProvider(client.ConnectionString);

                    //server -> client sync direction is DownloadOnly
                    var syncSetup = SyncDatabaseProvisioningSetting.GetSetup();

                    var options = SyncDatabaseProvisioningSetting.GetClientOptions();
                    options.Logger = SyncDatabaseProvisioningSetting.SyncLog;


                    var agent = new SyncAgent(clientProvider, serverProvider, options, syncSetup, SyncDatabaseProvisioningSetting.GetScope());

                    var remoteOrchestrator = agent.RemoteOrchestrator;
                    
                    remoteOrchestrator.OnDatabaseChangesApplying(args =>
                    {
                        //...Log stuff
                    });

                    remoteOrchestrator.OnTableChangesBatchApplying(args =>
                    {
                        //...Log stuff
                    });

                    // Once changes are applied
                    remoteOrchestrator.OnTableChangesApplied(args =>
                    {
                        Logger.Sync.Debug(
                            $"- Applied [{args.TableChangesApplied.State}] to table [{args.TableChangesApplied.TableName}]: Applied:{args.TableChangesApplied.Applied}. Failed:{args.TableChangesApplied.Failed}. Conflicts:{args.TableChangesApplied.ResolvedConflicts}. ");
                    });


                   
                    remoteOrchestrator.OnDatabaseChangesApplied(args =>
                    {
                        //...Log stuff
                    });

                    var progress = new SynchronousProgress<ProgressArgs>(
                        s => { Logger.Sync.Debug($"{s.Context.SyncStage}:\t{s.Message}"); }
                    );

                    Logger.Sync.Info("Sync Start");
                    
                    var result = agent.SynchronizeAsync(progress).ConfigureAwait(false).GetAwaiter().GetResult();

                    Logger.Sync.Info(result);
                    client.LastSyncStatistics = result;

                    TriggerOnSyncFinishedAsync(client.HostAndSQLInstance, "");
                    
                    
                }
				 catch (SyncException syncExp)
                {
                    Logger.Sync.Warn(
                        $"Encountered SyncException {syncExp.TypeName} {syncExp.Message}, Attempting Reconfiguration of server: {client.Hostname}.");
                    
                }
                catch (Exception ex)
                {
                    Logger.Sync.Error(ex.Message);
                    
                        Logger.Sync.Error($"Error occurred when performing sync with db {client.HostAndSQLInstance}.",
                            ex);
                        TriggerOnSyncErrorAsync(ex.Message, client.HostAndSQLInstance);
                    
                }

**Closed** 2021-11-25 11:56 UTC
