### ISSUE TITLE
Editing SyncSetup doesn't result in changes using SyncType.Normal. Reinitialize mode for each table instead of globally ?

### ISSUE THREAD

**Issue by matevzcesar** [Mimetis/Dotmim.Sync#397] opened 2021-01-12 09:04 UTC
Hello. 

I'm working on an android application that needs to sync data from a web server using SQL Server to Sqlite. I've been testing a scenario, which should be working judging by the documentation. I added an existing column to a table in the **sync setup** and ran the sync using SyncType.Normal. I was expecting to see the column sync to the client device, but instead it resulted in an updated schema, but all the rows were lost. If I run this using SyncType.Reinitialize it works, but for us, downloading everything again for such small changes is not an option.

Is this working as intended or is it a bug?

Also, if this is working as predicted, would a valid solution to this problem be, to have a custom API that would handle these changes (eg. update the schema, and insert data for all existing records) on app update, and then use a new version of DMS setup to sync from then on?

**Comment by Mimetis** [comment] 2021-01-12 09:09
The problem is coming from the timestamp
Once you have added the column, the next sync will download all rows from the last time you made a sync to now
Only the rows you have added (since the last sync) in your tables (including the new one) will be downloaded

That's why, when you are adding a new column, it is a good approach to make a `Reinitialize` sync.

**Comment by gentledepp** [comment] 2021-01-12 10:29
there are two cases I suppose:

1. adding a new column to a table and sync it
if you add a new column to some table, you will probably populate it with data (default data or using some custom logic). In that case, the tracking tables should be updated and you will get all the rows of that particular table again on the client.

2. Adding an existing column to a sync setup
If you, however, just add another column to be synchronized to the sync setup, but that column did exist before, then, technically speaking, those rows were never changed and, thus, will also not be synchorinized again


Am I right in that assumption?

**Comment by matevzcesar** [comment] 2021-01-12 10:51
My thinking is the same. What I have an issue with is, that when I tried the second scenario, the schema was changed but the **data was removed**. I don't see why this would happen.

**Comment by Mimetis** [comment] 2021-01-12 10:52
Can you elaborate a little bit more the issue ? I don't see why data is removed.

**Comment by matevzcesar** [comment] 2021-01-12 11:18
Sure. So I have a few tables synced on the client side. "Table1" contains 1 record, and is synced to the client. I then edit the sync setup, by adding a column to to that table as such: `setup.Tables["Table1"].Columns.AddRange(new string[] { "OldColumn", "NewColumn", "OldColumn2" });`

I then call `_agent.SynchronizeAsync(SyncType.Normal, progress)`, this exits with the message: `{Synchronization done. 
	Total changes  uploaded: 0
	Total changes  downloaded: 0 
	Total changes  applied: 0 
	Total resolved conflicts: 0
	Total duration :0:0:3.555 }`. If I the look into the database, the schema of "Table1" was actualy updated, so that it contains "NewColumn", but there is no records in this table anymore. The record on all other synced tables persist.
	
Let me know if you need any extra information.

**Comment by Mimetis** [comment] 2021-01-12 11:32
I understood already your scenario. 
My question was more about your sentence "data was removed" 
Do you have some data that disappear for no reasons  ?

**Comment by matevzcesar** [comment] 2021-01-12 11:38
Well yes, the record in "Table1" was gone on the client side after syncing.

**Comment by gentledepp** [comment] 2021-01-12 11:44
and apparently it is scenario (2): Adding an existing column to a sync setup

well, it then *is* necessary to re-sync the whole table that was affected. Otherwise this column will be empty on the client side. If you changed any of those `Table1` rows on the client and snyched those to the server, the  `NewColumn` of those rows will be cleared on the server side.

However, as I understand, currently you can only retinitialize **all** tables of a scope. You cannot reinitialize separate tables.

I think this could be a neat addition in the future: If a table changes, it needs to be reinitialized. But only that particular table. Right?

**Comment by matevzcesar** [comment] 2021-01-12 12:00
@gentledepp Yes, I think that'd be a great feature.

**Comment by Mimetis** [comment] 2021-01-12 12:54
Yes, one feature I already thought about would be to have the `Reinitialize` option on each table and not globally.
But, in that case, we will face a lot of constraints, like foreign keys constraints and so on.

Imagine your want to reinitialize **only** the `Customer` table, for some reason (for instance, like you said, because you've added one column in the setup object)
Well, we need to **Delete** all the `Customer` table records, then repopulate with the server records.

What happen to all foreign tables like `CustomerAddress` or any others ? The keys to the `Customer` table will make the delete failing, obviously.
Of course, we can rely on the `DisableConstraint` options, that's true (but what happened if you set `false` to this options ? )

And this is only a small thought on all the problems that can occurs and that I don't even imagine right now :)

Anyway, this is still a very good idea, thanks @gentledepp  and @matevzcesar for the feedback ! 
@matevzcesar if you have any more question on this particular problem, we can continue the discussion, otherwise you're welcome to close the issue.

**Comment by Mimetis** [comment] 2021-01-12 17:51
Well, actually, there is a way to accomplish what you need.
Unfortunatelly, it will be only available in the next release. (`v0.6`)
It relies on the `DbCommand` that are exposed through the **Interceptors** (Each time you're calling a `orchestrat.OnSomethingMethod()`) 

See https://github.com/Mimetis/Dotmim.Sync/discussions/391#discussioncomment-266769 for more info.

You can easily trick the `DbCommand` and replace it (on the server and on the client) to accomplish what you need:
- On the server, replacing the `SelectChanges` command by the `SelectInitializedChanges` : That way, you will globally make a `Select * from Table` and get all the rows, regardless the timestamp.
- On the client, just truncate the table before applying the rows to prevent conflicts.

Of course, this will work **ONLY** if you have set the option `DisableConstraintsOnApplyChanges` to `true` in your `SyncOptions` instance (it's the default value, by the way)

Here is a quick sample, wher I've added a new table **Employee** in my `SyncSetup`:

``` cs
// Adding a new table to an existing setup that has been used and synced several times before
existingSetup.Tables.Add("Employee");

// create an agent 
var agent = new SyncAgent(client, server, options, existingSetup);

// ON SERVER : When trying to get changes from the server, just replace the command with the Initialize command
// and get ALL the rows for the migrated new table
agent.RemoteOrchestrator.OnTableChangesSelecting(tcs =>
{
    if (tcs.Table.TableName != "Employee")
        return;

    var adapter = agent.RemoteOrchestrator.GetSyncAdapter(tcs.Table, existingSetup);
    var command = adapter.GetCommand(DbCommandType.SelectInitializedChanges);
    command.Connection = tcs.Connection;
    command.Transaction = tcs.Transaction;

    tcs.Command = command;
});

// ON CLIENT : Forcing Reset of the table to be sure no conflicts will be raised
// And all rows will be re-applied 
agent.LocalOrchestrator.OnTableChangesApplying(async tca =>
{
    if (tca.Changes.TableName != "Employee")
        return;

    var adapter = agent.LocalOrchestrator.GetSyncAdapter(tca.Changes, existingSetup);
    await adapter.ResetTableAsync(tca.Connection, tca.Transaction);
});

var s = await agent.SynchronizeAsync();

```

Make sense ?

**Comment by gentledepp** [comment] 2021-01-13 07:58
yes, makes sense.
However, there is a major flaw in the code.
You need to know which client currently tries to sync and track, if it already did this re-sync.
Otherwise, this new table "Employee" will _always_ be re-synced _for all_ clients.

What would be the best approach to achieve this?

**Comment by Mimetis** [comment] 2021-01-13 10:49
## Tracking Client timestamp on Server

Tracking the client on the server side was a solution we had in earlier version (< `v4.0` I guess) and it leads to major issues (sorry don't remember exactly, but I guess we can find some of them in old issues / discussions. If I remember well, if something bad happened during sync (timeout or whatever) we could ended with a situation where server did not had the same timestamp info as the client)

Today `DMS` server side is *agnostic* to any client.
That means that the client is the only responsible to know what he wants (and most important **when** )
And by the way, you can have a **servers cluster** to allow clients to sync with any of them, since server just ... does not care :)

So far:
- **Client** stores its own `LastTimeStamp` and the `ServerLastTimeStamp` version as well in `scope_info`
- **Server** stores historical data with the client timestamp as well in `scope_info_history`, but this timestamp is just here for any kind of reporting you would want to expose on the server side.

## Client Migration
Regarding if we have a solution to know if a migration has been done during the sync, we have this information on the client side, when a `Migration` is done:

``` cs
agent.LocalOrchestrator.OnMigrated(ma =>
{
    // migrateTables are empty if not migration tables has been done.
    var migratedTables = ma.Migration.Tables;
    
    foreach(var migratedTable in migratedTables)
    {
        var tableName = migratedTable.SetupTable.GetFullName();

        // enum MigrationAction {None,CreateOrRecreate,Drop,Rename}
        var migrationActionStoredProcedure = migratedTable.StoredProcedures;
        var migrationActionStoredTable = migratedTable.Table;
        var migrationActionStoredTrackingTable = migratedTable.TrackingTable;
        var migrationActionStoredTriggers = migratedTable.Triggers;
    }
});

```

So far, we can store this information and then hook `OnTableChangesApplying` for the migrated tables

This solution is good for the client side, but it does not resolve the server side, since everytime we will send the entire table.


## Server side

**In progress redaction, need to restart**

**Comment by gentledepp** [comment] 2021-01-14 09:38
Well this sounds absolutely ok to me.
One more thought:
The approach that I proposed would also work:

* client synchronizes and requests server changes since server timestamp **s0**  - stores new server timestamp **s1**
*  servers sync configuration is changed: We add a column `newcolumn` to table `employee` at **s2**
*  client requests changes again that happened since **s1**. Because the server knows that after **s1** the employee table was changed, it initiates a reinitialization of the table `employee`. Now the client applies those changes and stores **s3**
*  after some time, the client again requests changes since **s3**. Since no configuration/table changes have been performed since then, the sync process runs as usual

This implementation would ensure, that the clients always have the latest data and server schema.
One additional benefit is that it would still be **doable with just one request**. (I know, I am annoying with my "request counting"... sorry for that @Mimetis )

However, the downside would be: The client cannot choose if it actually wants to have all that data.
Maybe the new column would break the older version of a client as it does not expect this column.
Then, your approach would be better. The client could decide to not migrate the scopes. And we could develop a new version of the app that just performs this schema migration once it synchronizes the first time.


Now my question is: How exactly does this schema migration work?
Is this always on, or can I opt out and keep my old client schema?
In that case, does the sync still work?

**Comment by Mimetis** [comment] 2021-01-14 10:22
I'm currently working on the **Migration** part today :) 

First of all, I have added something you asked for several times. The migration will apply an `Alter Table` when new column are added to a sync table (instead of `Drop` & `Create`)

I've re worked the migration part to ensure that the migration will **Never** drop a table or a column:
- If you are adding a column in your `SyncSetup`, the `DMS` fx will perform an `Alter Table Add Column`
- If you are removing a column from your `SyncSetup`, the `DMS` fx won't perform anything.
  - Mainly because you may want to remove a column from the sync process, but you want to keep the column in your table.
  - You have the possibility to remove any column if needed with your own code, I guess ;)
- If you adding a table, `DMS` will add this table to the client side.
- If you removing a table, `DMS` will remove the stored procedures, tracking tables and triggers, but ,not the table.

Furthermore, during the migration, you have access to an `OnMigrating` interceptor; where all the removed/added/alter tables are accessibles, with the action suggested (Drop, Create, Alter, None)
You can change all the action for each object (stored proc, triggers, tracking table, table)

Regarding the last question: *sync still work ?*
Well, it depends on what you've done during the migration. If you don't intercept anything, it should work as expected :)

**Comment by gentledepp** [comment] 2021-01-14 10:32
O my god... you are coding a birthday present for me 😍 (Today it's actually my bd ;-)) This sounds awesome!!

Btw. I am still working on improving the old dms version from waaaaaaaay back, because we cannot migrate to the new one so easily as it introduces breaking changes.
Thereby, I had to change several internal implementations to overcome issues. I wrote them all down and would like to open an "improvement" discussion/issue once they've proven to be helpful in production.

**Comment by Mimetis** [comment] 2021-01-14 10:43
Hey Happy new year dude !

For all the improvements, you can open a discussion for sure.
For the migration implementation, I hope to commit something by the end of the day
Stay tunned

**Comment by MaTToX3** [comment] 2021-01-15 15:30
> 
> ## Tracking Client timestamp on Server
> 
> Tracking the client on the server side was a solution we had in earlier version (< `v4.0` I guess) and it leads to major issues (sorry don't remember exactly, but I guess we can find some of them in old issues / discussions. If I remember well, if something bad happened during sync (timeout or whatever) we could ended with a situation where server did not had the same timestamp info as the client)
> 
> Today `DMS` server side is _agnostic_ to any client.
> That means that the client is the only responsible to know what he wants (and most important **when** )
> And by the way, you can have a **servers cluster** to allow clients to sync with any of them, since server just ... does not care :)
> 
> So far:
> 
>     * **Client** stores its own `LastTimeStamp` and the `ServerLastTimeStamp` version as well in `scope_info`
> 
>     * **Server** stores historical data with the client timestamp as well in `scope_info_history`, but this timestamp is just here for any kind of reporting you would want to expose on the server side.
> 
> 
> Finally, your suggestion is good, the only thing to do is to replace "Server knows client needs this table to reinit", by "Client sends a note to Server to let the server knows it needs to reinit"
> 
> To achieve this, we can use the `SyncContext` instance that is shared between the server and the client.
> 
> Here is my suggestion:
> ## Client Migration
> 
> Regarding if we have a solution to know if a migration has been done during the sync, we have this information on the client side, when a `Migration` is done:
> 
> ```cs
> agent.LocalOrchestrator.OnMigrated(ma =>
> {
>     // migrateTables are empty if not migration tables has been done.
>     var migratedTables = ma.Migration.Tables;
>     
>     foreach(var migratedTable in migratedTables)
>     {
>         var tableName = migratedTable.SetupTable.GetFullName();
> 
>         // enum MigrationAction {None,CreateOrRecreate,Drop,Rename}
>         var migrationActionStoredProcedure = migratedTable.StoredProcedures;
>         var migrationActionStoredTable = migratedTable.Table;
>         var migrationActionStoredTrackingTable = migratedTable.TrackingTable;
>         var migrationActionStoredTriggers = migratedTable.Triggers;
>     }
> });
> ```
> 
> The `SyncContext` instance is shared between **Client** And **Server** and we can use the `Dictionary<string, string> AdditionalProperties` property to signal to the server what we want to hook.
> 
> The code becomes:
> 
> ```cs
> // On client
> agent.LocalOrchestrator.OnMigrated(ma =>
> {
>     // migrateTables are empty if not migration tables has been done.
>     var migratedTables = ma.Migration.Tables;
> 
>     foreach (var migratedTable in migratedTables)
>     {
>         var tableName = migratedTable.SetupTable.GetFullName();
>         
>         // Adding this table in the sync context 
>         if (migratedTable.Table == MigrationAction.CreateOrRecreate)
>         {
>             if (ma.Context.AdditionalProperties == null)
>                 ma.Context.AdditionalProperties = new Dictionary<string, string>();
> 
>             ma.Context.AdditionalProperties.Add(tableName, "Reinitialize");
>         }
>     }
> });
> ```
> 
> The second step on the client is still the same, just changing the hard coded `Employee` value with the `SyncContext.AdditionalProperties` thing:
> 
> ```cs
> // ON CLIENT : Forcing Reset of the table to be sure no conflicts will be raised
> // And all rows will be re-applied 
> agent.LocalOrchestrator.OnTableChangesApplying(async tca =>
> {
>     if (tca.Context.AdditionalProperties == null || tca.Context.AdditionalProperties.Count <= 0)
>         return;
> 
>     if (tca.Context.AdditionalProperties.ContainsKey(tca.Changes.GetFullName()))
>     {
>         var addProp = tca.Context.AdditionalProperties[tca.Changes.GetFullName()];
>         if (addProp == "Reinitialize")
>         {
>             var adapter = agent.LocalOrchestrator.GetSyncAdapter(tca.Changes, setup);
>             await adapter.ResetTableAsync(tca.Connection, tca.Transaction);
>         }
>     }
> });
> ```
> 
> ## Server side
> 
> This solution is good for the client side, but it does not resolve the server side, since everytime we will send the entire table.
> But thanks to the additionnal properties, we have a solution here
> 
> ```cs
> // ON SERVER : When trying to get changes from the server, just replace the command with the Initialize command
> // and get ALL the rows for the migrated new table
> agent.RemoteOrchestrator.OnTableChangesSelecting(tcs =>
> {
>     if (tcs.Context.AdditionalProperties == null || tcs.Context.AdditionalProperties.Count <= 0)
>         return;
> 
>     if (tcs.Context.AdditionalProperties.ContainsKey(tcs.Table.GetFullName()))
>     {
>         var addProp = tcs.Context.AdditionalProperties[tcs.Table.GetFullName()];
>         if (addProp == "Reinitialize")
>         {
>             var adapter = agent.RemoteOrchestrator.GetSyncAdapter(tcs.Table, setup);
>             var command = adapter.GetCommand(DbCommandType.SelectInitializedChanges);
>             command.Connection = tcs.Connection;
>             command.Transaction = tcs.Transaction;
> 
>             tcs.Command = command;
>         }
>     }
> });
> ```
> 
> It's tricky, but It's working (currently working on different use cases, with Web API, Filters and Schema. I will do the tests as well)
> But since, in my opinion, changing a database schema implies, most of the time, a full resync, this scenario is at the edge.
> 
> Does it make sense, and is it acceptable for you ?

I have tried that, no luck. It left me wondering, does it work only if transfering data via TCP?

**Comment by Mimetis** [comment] 2021-01-15 15:36
*(I have edited your post, because we don't need to quote the whole message, since it's a very long message copy / paste for nothing) :)*

This code works only on the last mastre branch source code (not yet published on nuget)

It should work on Web API too, but the code is slightly different, since the `RemoteOrchestrator` is not directly available from the `SyncAgent`, but instead in your Web Api controller, through `WebServerManager.GetOrchestrator`

**Comment by MaTToX3** [comment] 2021-01-15 15:49
Thanks for a quick reply! 

Yes, I was aware of the web api implementation however I was unable to access the GetSyncAdapter method thats why I was confused. But of course I used nuget beta package thats why. 

Thanks again and sorry for a full reply.

**Comment by Mimetis** [comment] 2021-01-23 19:10
@MaTToX3 The last version has been released :)

**Closed by Mimetis** 2021-01-23 19:10 UTC
Labels: enhancement, help wanted
