### ISSUE TITLE
Bulk Data :  Xamarin app Hangs after downloading data Please Help

### ISSUE THREAD

**Issue by PardeepBhandari** [Mimetis/Dotmim.Sync#368] opened 2020-12-05 16:08 UTC
This work very fine for some rows but if the data is large my xamarin app gets hang it download all the data in small request but hang after that. In testing It download around 200 mb of data but hang after that.

				string APIString = eMuneem.CommonFunctions.ServerAPIUrl + "sync?Server=" + result.ServerIP + "&DBName=" + result.DBName + "&UserID=" + result.DBUserID + "&Password=" + result.DBPassword;

                var handler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.None };
                var client = new HttpClient(handler) { Timeout = TimeSpan.FromMinutes(30) };

                var RemoteServerProvider = new WebClientOrchestrator(APIString, null, null, client);
                var clientProvider = new SqliteSyncProvider(App.LocalDbFullPath);

                var progress = new SynchronousProgress<ProgressArgs>(args => ValidationMessage = ($"{args.Context.SyncStage}:{args.Message}"));

                var tables = new string[] { "Accounts" };

                var syncSetup = new SyncSetup(tables);

                var clientOptions = new SyncOptions {  DisableConstraintsOnApplyChanges = true, ConflictResolutionPolicy = ConflictResolutionPolicy.ServerWins, BatchSize=200, UseBulkOperations=true, ScopeInfoTableName = "masterscopetable" };

                var agent = new SyncAgent(clientProvider, RemoteServerProvider, clientOptions, syncSetup);

                var s1 = await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Normal, progress);

**Comment by Mimetis** [comment] 2020-12-05 23:29
Try with multiple scopes to divide the memory used by the xamarin app

**Comment by PardeepBhandari** [comment] 2020-12-06 14:43
Very thanks for quick response

Sql database size is 272 mb

table sizes
Table                              | Rows     |Resereved  |Data in KB
dbo.Transactions           | 530,882 | 126,856     | 126,544 | 224 | 88
dbo.ItemDataFooter      | 22,192  | 14,920       | 14,800    | 40 | 80
dbo.Accounts                | 3,136    | 2,696          | 2,640      | 16 | 40
dbo.Item                        | 100      | 144             | 72           | 16 | 56
dbo.scope_info_server  | 1           |  64              | 56          | 8 | 0
dbo.scope_info_history | 1           | 16               | 8            | 8 | 0
dbo.Series                     | 26         | 16               | 8            | 8 | 0
dbo.Accounts_tracking | 0           | 0                 | 0            | 0 | 0

now I used batch size 2000 only for single table Accounts. 
On Xamarin Page Last progress message is [main] Change Selected upserts:0 deletes:0 total:0
it hang on there
I test it on mobile also and inspect each request . It download whole table in json format but hang there after.

It works very fine when no of rows below 100 .
but when i crease no of rows to 300 it hangs there.
 out put window text are below

[output text.txt](https://github.com/Mimetis/Dotmim.Sync/files/5648915/output.text.txt)

**Comment by Mimetis** [comment] 2020-12-10 09:05
I think You should have raised an `OutOfMemoryException` somewhere.
The Upsert action is transactional so far, once the data have been downloaded on the client, the application will try to insert / update / delete all the rows in one single transaction.
Not sure about that, but it could definitively be your problem here

My guess would be to make multiple sync, using a filter.
Let's say, making a filter on a column category for example, that will divide the table content in 4 or 5 chunks.

Let me know if it helps or not

**Comment by PardeepBhandari** [comment] 2020-12-10 13:17
How Can I Set up Vertical filter i.e

1. ID >1 And ID < 100
2. ID > 101 And ID < 200

**Comment by Mimetis** [comment] 2020-12-10 14:31
With a CustomWhere https://dotmimsync.readthedocs.io/Filters.html
But I think a filter based on a category or something like that, should be a better solution

**Comment by PardeepBhandari** [comment] 2020-12-14 07:27
Please provide example for custom where server side and client side
and also how can i pass where string from client side.

actually i want to sync large data in chunk of 50 rows at a time in a loop

3000 rows 3000/50 = 60 sync in a loop

because i am not able to sync large data in a single sync

one more question am i only person who is facing this issue while syncing large data  

i need to sync 50000 rows for a single table this table stores all the transactions information dr , cr etc.

**Comment by PardeepBhandari** [comment] 2020-12-22 06:18
Hi
There is a column GroupID in table Accounts
In First Sync I set the parameter GroupID value =13 after sync I get 300 rows in xamarin app
In Second Sync I Change the value of Parameter to 15 but no of rows remain same although there are 70 rows  of value GroupID = 15 in sql server database.

Code on server side

 var setup = new SyncSetup(tables);
 var addressFilter = new SetupFilter("Accounts");
 addressFilter.AddParameter("GroupID", "Accounts",true);
 addressFilter.AddWhere("GroupID", "Accounts", "GroupID");
 setup.Filters.Add(addressFilter);

Code on child side

                if (!agent.Parameters.Contains("GroupID"))
                {
                    agent.Parameters.Add("GroupID", 10);
                }

                var s1 = await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Normal, progress);

Please provide help for CustomWhere also

**Comment by Mimetis** [comment] 2020-12-22 10:34
Because on the second sync process, you get all the lines **Modified, Deleted or Added** from the **last time** you made a sync, to now.

It seems that you do not have any rows changed from the last time you sync, that have the group id == 15

Here is a detailed explanation:

- First sync : From T0 to T1 : You get all the rows from your DB that have GroupId = 13
- Second Sync : T1 to T2 : You change the filter (BAD IDEA) and then you get all the rows from T1 to T2 that have filter GroupId = 15

I assume you want the rows from T0 to T2 with groupId = 15, right ?
So far, you need to make a full resync with a `Reninitialize` mode to get all the filtered rows for GroupID = 15
BUT, in that case, you will lost all the rows with GroupID = 13
Does it make sense ?

**Comment by PardeepBhandari** [comment] 2020-12-22 11:06
Ok it works like  replication. Now I got the concept of filters but my question remain same how can I sync large data in pieces of small chunks without applying filters. I think custom filters will behave same.

In merge replication it works fine if we sync large data. Plz help it is almost 4 months and I am stuck.

**Comment by Mimetis** [comment] 2020-12-22 13:54
You may have a problem with your xamarin application within your device.
If you have not enough memory on the device you may encounter some serious problems.

Depending on your answers, we will try to find a solution:
- Do you have a lot of tables, and the sum of all of them is too large ?
- Do you have only one table that is too large ?

**Comment by PardeepBhandari** [comment] 2020-12-22 13:57
I have to sink 6 tables two of them have large data above 50 to 100 thousand rows and in one table columns are above 125 in seconds 20 columns. Mostly float data types.

**Comment by Mimetis** [comment] 2020-12-22 14:05
Depending on the relations between your tables, I would suggest you to make two sync


- 1 sync with a set of small tables + 1 big table
- 1 sync with  all others tables + the other big table

If it's still not working, try
- 1 sync with all small tables
- 1 sync with 1 big table
- 1 sync with other big table

On your client, declare 3 `SyncSetup`, 3 `SyncAgent`
Run each agent in sequence, not parrallel.
Wait for the 1st one to success, before sending the 2nd one

On your server, declare 3 `SyncSetup` as well, and add 3 SyncServer services

Let me know

**Comment by PardeepBhandari** [comment] 2020-12-22 16:22
It even don't sync small table accounts which has 3000 rows and 50 columns application hang after downloading data. Previously you said I have to break table in 4 to 5 chunks . Plz explain how can I sync large data without applying filter and memory issue.

**Comment by Mimetis** [comment] 2020-12-22 16:29
It should work even with 50 columns, if you have 3k rows
Is it working when not running in a xamarin app (for instance, running from a console application) ?

**Comment by PardeepBhandari** [comment] 2020-12-23 05:38
Yes it is true it sync data from a window application for all tables with large data in one sync . it take some minutes but ok.
but i need to sync from xamarin app.

**Comment by PardeepBhandari** [comment] 2020-12-30 17:06
Sir Please help . it will help my carrier I need this.

**Comment by Mimetis** [comment] 2020-12-30 18:15
I don't need the full solution, just the code you're using in the xamarin app for sync, and the controller from the web api

And more important, I need the schema you are syncing, because I need to test a fail situation

That 's why I need from you:
- A sample Xamarin application with one page, one single button, and the code behing this button is launching the the sync process, like u are doing in your full solution
- The web api server project to ensure everything is fine
- A sample database, with no sensitive data

These 3 resources should allow me to reproduce ur bug

Meanwhile, please remove the files you are sharing, because someone could potentially get them and used them without any concent from you

BTW, I've just take a look at your code, please don't use `SynchronousProgress` in a xamarin app, it should be used only from a console application,  just use `Progress`

**Comment by PardeepBhandari** [comment] 2021-01-08 09:33
Hi I removed unimportant code from both solution please consider and help 
Web API
[StarPickupMVC.zip](https://github.com/Mimetis/Dotmim.Sync/files/5786333/StarPickupMVC.
zip)

Packages Required For Web API
![packages 1](https://user-images.githubusercontent.com/43168662/103998579-28814d80-51c2-11eb-8be7-66fe4d0acc49.png)
![packages 2](https://user-images.githubusercontent.com/43168662/103998595-2a4b1100-51c2-11eb-93d6-93ad95f1c283.png)

Sample App
[SampleApp.zip](https://github.com/Mimetis/Dotmim.Sync/files/5786342/SampleApp.zip)
 database backup file Sql Server version 10.5
[ltd.zip](https://github.com/Mimetis/Dotmim.Sync/files/5786354/ltd.zip)
I need to sync all the tables

**Comment by PardeepBhandari** [comment] 2021-01-09 05:33
plz Help

**Comment by Mimetis** [comment] 2021-01-09 14:28
You have too many columns in your `Accounts` table.
**You. Have. 170 Columns. In. That. Table. IT. IS. WAY. TOO. MUCH.**

.. but it works. it's way too slow, but it's working...

By tge way, don't use `SynchronousProgress<T>`. This thread bind object is meant to be used ONLY with console application. Consider using `Prorgess<T>` instead.

Despite this, it's working on my Xamarin emulator. 
It takes almost `4 min` to complete on **Debug** mode and `1.20 min`, on a `Release` mode.

![image](https://user-images.githubusercontent.com/4592555/104093837-757e2600-528d-11eb-85a4-6bb1714dfba3.png)

Here is the code I'm using:

Xamarin Code: 

``` xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="XamAppSync.MainPage">

    <StackLayout>
        <Frame BackgroundColor="#2196F3" Padding="24" CornerRadius="0">
            <Label Text="Welcome to Xamarin.Forms!" HorizontalTextAlignment="Center" TextColor="White" FontSize="36"/>
        </Frame>
        <Button Text="Sync" Clicked="Handle_Clicked" />
        <Label Text="Results" FontSize="Title" Padding="30,10,30,10"/>
        <Label Text="" x:Name="lblProgress" FontSize="10" Padding="30,0,30,0"/>
        <Label Text="" x:Name="lblResult" FontSize="16" Padding="30,10,30,0"/>
    </StackLayout>

</ContentPage>

```


``` cs
private async void Handle_Clicked(object sender, System.EventArgs e)
{
    try
    {
        // Use this when you want to use sqlite on ios
        SQLitePCL.Batteries_V2.Init();

        // 10.0.2.2 is a special url to be able to reach the machine localhost web api
        var serverOrchestrator = new WebClientOrchestrator("http://10.0.2.2:50886/api/sync");

        // Path the local sqlite database
        string dbPath = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "SqliteDatabase4.db3");

        var clientOptions = new SyncOptions { BatchSize = 5000, ScopeInfoTableName = "masterscopetable" };

        // Sqlite Client provider
        var clientProvider = new SqliteSyncProvider(dbPath);

        // Creating an agent that will handle all the process
        var agent = new SyncAgent(clientProvider, serverOrchestrator, clientOptions);

        var progress = new Progress<ProgressArgs>(args => lblProgress.Text = $"{args.Context.SyncStage}:{args.Message}");

        // Launch the sync process
        var s1 = await agent.SynchronizeAsync(progress);

        // See results
        lblResult.Text = s1.ToString();
    }
    catch (Exception ex)
    {
        lblResult.Text = ex.Message;
    }
}
```

Asp.Net Core Web Api:

``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services.AddMemoryCache();

    var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];
    var tables = new string[] {"Accounts" };
    var syncSetup = new SyncSetup(tables);
    services.AddSyncServer<SqlSyncProvider>(connectionString, syncSetup);
}
```
``` cs
[ApiController]
[Route("api/[controller]")]
public class SyncController : ControllerBase
{
    // The WebServerManager instance is useful to manage all the Web server orchestrators register in the
    private WebServerManager webServerManager;

    // Injected thanks to Dependency Injection
    public SyncController(WebServerManager webServerManager) => this.webServerManager = webServerManager;

    /// <summary>
    /// This POST handler is mandatory to handle all the sync process
    /// </summary>
    /// <returns></returns>
    [HttpPost]
    public async Task Post() => await webServerManager.HandleRequestAsync(this.HttpContext);

    /// <summary>
    /// This GET handler is optional. It allows you to see the configuration hosted on the server
    /// The configuration is shown only if Environmenent == Development
    /// </summary>
    [HttpGet]
    public async Task Get() => await webServerManager.HandleRequestAsync(this.HttpContext);
}
```

### Reducing the columns number

Now, If you can consider reducing the columns number and split in several tables (let's say `Account`, `AccountUser`, `AccountAddresses` etc....), you will see that you will have a tremendous performance gain.

Here is a quick sample, using only a small amount of columns from your `Account` table:

``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services.AddMemoryCache();

    var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];
    var tables = new string[] {"Accounts" };
    var syncSetup = new SyncSetup(tables);
    syncSetup.Tables[0].Columns.AddRange(new string[] { "ID", "Account", "GroupID" });

    services.AddSyncServer<SqlSyncProvider>(connectionString, syncSetup);
}

```
As you can see, I'm specifying only 3 columns, and here are the performances:

- **Debug Mode** : `170` columns : `4` min
- **Debug Mode** : `3` columns : `10.5` sec
- **Release Mode** : `170` columns : `1.2` min
- **Releae Mode** : `3` columns : `2` sec

**Comment by PardeepBhandari** [comment] 2021-01-11 07:50
Hi
my app can sync whole accounts table in 7 secs. thanks for that.

now there is another table Transactions with few columns i mention below. no of rows are 530882.
can you please check that.
          
 var tables = new string[] { "Transactions" };
 var setup = new SyncSetup(tables);
 setup.Tables[0].Columns.AddRange(new string[] { "ID", "Series" ,"EntryNo", "SrNo", "Invoice" , "Voucher_Date", "Status", "rowguid" , "Voucher_Name","Narration","Particular","Dr","Cr", "Account" });

Thanks

**Comment by Mimetis** [comment] 2021-01-11 08:21
This section is all about "**Issues**"
Since your question is not an *issue* but more  a "*Do It For Me" question, I will let you figure out how to make it work properly
Please
- Use **Issues** to post issues
- Use Markdown to format your code in a post

I will close this issue, since it is resolved
Thanks

**Closed by Mimetis** 2021-01-11 08:21 UTC

**Comment by PardeepBhandari** [comment] 2021-01-11 10:26
Thanks for your HELP.

**Comment by Mimetis** [comment] 2021-01-21 16:34
Batchsize is better when between **2000** and **6000**
I Think **200000** is a little bit too much (since it's approximatively... 200 Mo per http request !! :o )
