### ISSUE TITLE
Can't get working in WinForms

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#663] opened 2021-12-15 09:20 UTC
I have a class library containing a number of winforms. I am trying to implement this. My understanding is to use a version of .net framework containing v2.0 but I am getting all sorts of errors. Have I missed something?

My SQLite database is password protected and I am using classic .Net 4.8

**Comment by Mimetis** [comment] 2021-12-15 10:23
No idea.
I just tried in a .net core winforms application, and it's working.
![image](https://user-images.githubusercontent.com/4592555/146168691-9a945e3b-c14f-4385-96df-c0245a3dc767.png)


If you are using the classic .Net Framework (ie <= 4.8) you should resolve the sqlite installation before, I guess

**Comment by spj-uk** [comment] 2021-12-15 10:28
Ok, forgot to add I am using classic .net framework v4

**Comment by Mimetis** [comment] 2021-12-15 10:29
Try to find examples where sqlite is used, before trying to sync anyhting

**Comment by Mimetis** [comment] 2021-12-15 10:43
Ok i found a way

- Install nuget package `Microsoft.Data.SqlClient`  version` 3.0.1`
- install nuget package `Microsoft.Data.Sqlite` version `5.0.3`
- install nuget package `Dotmim.Core` , version >= `0.9`
- install nuget package `Dotmim.Sync.Sql` , version >= `0.9`
- install nuget package `Dotmim.Sync.Sqlite` , version >= `0.9`

**Comment by spj-uk** [comment] 2021-12-15 11:41
I get the followng error 

Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```
 var serverProvider = new SqlSyncProvider(serverConnectionString);

            // Second provider is using plain old Sql Server provider, relying on triggers and tracking tables to create the sync environment
            var clientProvider = new SqliteSyncProvider(clientConnectionString);

            //var clientProvider = new SqliteConnectionStringBuilder();
            //clientProvider.DataSource = clientConnectionString;
            //clientProvider.Password = "s/f6js2TpX)xP@Sh";



            // Tables involved in the sync process:
            var tables = new string[] {"table1", "table2", "table3" };
            MessageBox.Show("Start");

            // Creating an agent that will handle all the process
            var agent = new SyncAgent(clientProvider, serverProvider, tables);

            try
            {
                do
                {
                    // Launch the sync process
                    var s1 = await agent.SynchronizeAsync();
                    // Write results
                    Console.WriteLine(s1);
                    MessageBox.Show(s1.ToString());

                } while (Console.ReadKey().Key != ConsoleKey.Escape);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
                MessageBox.Show(ex.InnerException.ToString());
            }
```

**Comment by Mimetis** [comment] 2021-12-15 12:29
I don't know.
You have a sample here that is working fine : https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/WindowsFormsClassic

I will close the issue since it's not related to `DMS`

If you found that the issue is coming from `DMS` and you are able to reproduce it, feel free to re open it.

**Closed by Mimetis** 2021-12-15 12:29 UTC
