### ISSUE TITLE
MySQL  Dotmin.Sync.SimpleConsole for Adventureworks

### ISSUE THREAD

**Issue by KenGrant** [Mimetis/Dotmim.Sync#251] opened 2020-04-07 16:26 UTC
I have an error running Dotmin.Sync.SimpleConsole for Adventure works on MySQL - 5.5.62-0 ubuntu0.14.04.1.

I would be grateful for any help. it is occuring in the function below:

private MySqlCommand BuildUpdateCommand(bool hasMutableColumns)

From Console :

Sync Start
BeginSession:   17:19:12.300
ScopeLoading:   17:19:12.443     Id:67f96467-4df0-4d03-9da7-a7dfdd9bf227 LastSync: LastSyncDuration:0
BeginSession:   17:19:13.36
SchemaRead:     17:19:15.617     Synced tables count: 9
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTO sync_row_count;
IF (sync_row_count = 0) THEN
        INSERT INTO `ProductDescrip' at line 26

**Comment by Mimetis** [comment] 2020-04-07 16:36
Can you try with the last source code from branch v0. 5 plz?

**Comment by KenGrant** [comment] 2020-04-07 16:57
Appreciate the fast reply - amazing!

I have tried Branch 0.5 - 

After changing SynchronizeAsync to reflect MySQL and removing additional port in DbHelper

//builder.Port = 3307; - Not sure what this is for?
________________________________________________________
private static async Task SynchronizeAsync()
    {
        // Create 2 Sql Sync providers
        var serverProvider = new MySqlSyncProvider(DbHelper.GetMySqlDatabaseConnectionString(serverDbName));
        //var clientProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(clientDbName));
        var clientProvider = new SqliteSyncProvider("clientX.db");
________________________________________________________
Console Output:

Sync Start
BeginSession:   17:50:03.435
ScopeLoaded:    17:50:03.611     [main] [DefaultScope] [Version ] Last sync: Last sync duration:0:0:0.0
ScopeLoaded:    17:50:04.776     [adventureworks] [DefaultScope] [Version ]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTO sync_row_count;
IF (sync_row_count = 0) THEN
        INSERT  INTO `ProductDescri' at line 26

**Comment by Mimetis** [comment] 2020-04-07 17:39
Can you share with me the schema used for the mysql database ? especially the table which have a problem ?

I need to know what is the command text generated, to see what kind of problem you have.
That's strange, because I can't reproduce the error locally

**Comment by Mimetis** [comment] 2020-04-07 17:40
Oh, wait.
Can you describe your test scenario ? which kind of Server (SQL, MYSQL) ? which kind of client (SQL, MYSQL, SQLITE) ?

**Comment by KenGrant** [comment] 2020-04-07 17:42
HI Sébastien

Many thanks for replying – hope you don’t mind the direct contact?

Can I pick this up with you tomorrow? I am stopping now for today.

Stay safe.

Ken

**Comment by Mimetis** [comment] 2020-04-07 17:44
Good evening so :)

**Comment by Mimetis** [comment] 2020-04-14 23:17
Feel free to comment here, if you're still have the issue.
For now, I will close it and will re-open it, if you still have concerns

**Closed by Mimetis** 2020-04-14 23:17 UTC
