### ISSUE TITLE
BLOB row with large image

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#476] opened 2021-02-24 11:44 UTC
DMS version: 0.6.1
Server: mySQL
Local: SQLite
Table count: 10
Total rows: 1000000

I try to upload blob row from sqlite to mySQL, with images around 1.4MO per image. When looking at server, all images are not fully uploaded.
I suspect a timeout or some limitations. How to insure full upload?

**Comment by Mimetis** [comment] 2021-02-24 11:48
Do not use images in database that are >500ko
Otherwise try to increase batch size to 3000 or 4000
Try to compress image on device to reduce size

**Comment by sylverbee** [comment] 2021-02-24 12:17
Correction : each image is 95Ko ; 1.4Mo total.
Even with batch at 9000, I'm not able to full upload an image. And I wait until sync is done.

**Comment by Mimetis** [comment] 2021-02-24 13:25
Hum...
If sync is completed successfully, I guess the problem is not coming from DMS. 
Are you sure you saved the image locally correctly?

**Comment by sylverbee** [comment] 2021-02-24 15:41
Yes, of course.
DMS is working: I get update for VARCHAR field. But not for BLOB one.

**Comment by Mimetis** [comment] 2021-02-24 16:57
I guess we can close this issue since it seems the problem is not coming from `DMS` ?

**Comment by sylverbee** [comment] 2021-02-24 17:15
I'm not so sure. Yes, it works for INT/VARCHAR. But why not for BLOB?

=> I can store image in SQLite.
=> I can store image in mySQL.
=> Images stored in mySQL are download in SQLite
/!\ Images stored in SQLite are not uploaded in mySQL

You should investigate a bit before we close.

**Comment by Mimetis** [comment] 2021-02-24 17:20
Please share a simple repro, if you can, will be easier to debug

**Comment by sylverbee** [comment] 2021-02-24 17:22
What do you expect from me? Code?

**Comment by Mimetis** [comment] 2021-02-24 17:36
Maybe your MySql Column is not large enough ?

**Comment by sylverbee** [comment] 2021-02-24 17:40
It is.
1) it's a LONGBLOB
2) when I directly import an image in mySQL, it stores it. And I get a full image in SQLite through sync.

That's why I think it's something with DOTMIM and upload.

**Comment by Mimetis** [comment] 2021-02-24 17:56
are you able to create a small sample that reproduce the bug?

**Comment by sylverbee** [comment] 2021-02-25 06:56
I can reproduce the bug everytime with actual app.

**Comment by sylverbee** [comment] 2021-02-25 15:21
Another strange point: the size of an image synchronized through DOTMIM is always the same (8000 octets)

**Comment by Mimetis** [comment] 2021-02-25 15:27
Can you check the size of the sqlite column?
Maybe DMS has limited the size of the column during creation

**Comment by sylverbee** [comment] 2021-02-25 15:35
Everything is OK in SQLite: I can visualize the image.

I made another test with a **png file of 3,93Ko** => the file is fully synchronized in MySQL
With a **png file of 82ko** => the file in MySQL is again limited to 8Ko !

So I suspect something in DOTMIM. Once again, to be sure sync is fully done, I block application until the end of agent.SynchronizeAsync()

**Comment by Mimetis** [comment] 2021-02-25 17:43
hey @sylverbee 
Seems there is a bug with **MySql** stored procedures.
Can you check the stored procedure `TABLE_Update` and see what is the declaration type for your blob paramater.

Here is what you may have, and this is a bug. 
Supposing your column name is something like `Image`, in this example:
``` sql
	in_Image VarBinary(8000) ,
```

If it's the case, can you change this declaraction to:
``` sql
	in_Image LONGBLOB  ,
```

And see if everything is now working as expected ?

If you confirm the issue is fixed, the fix will be applied on the next release (meanwhile, you just need to replace the incorrect declaration with the good one, as said here)

**Comment by sylverbee** [comment] 2021-02-25 18:16
I made change on mySQL but now I get an error when trying to sync: `One or more errors occurred. (Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '=')`

**Comment by Mimetis** [comment] 2021-02-25 18:18
Sorry, this is related to your mysql server, not DMS

**Comment by sylverbee** [comment] 2021-02-26 06:22
> Sorry, this is related to your mysql server, not DMS

So it means the tables _tracking created by DOTMIM don't respect database encoding

**Comment by sylverbee** [comment] 2021-02-26 06:29
> Sorry, this is related to your mysql server, not DMS

All mySQL tables are now encoded into utf8mb4_unicode_ci. But keep having the error

NB : this message appears till I changed procedure _update to have a LONGBLOB.

**Comment by Mimetis** [comment] 2021-02-26 08:30
DMS does not change the encoding

**Comment by sylverbee** [comment] 2021-02-26 08:36
> DMS does not change the encoding

I mean tables created by DMS for tracking don't reuse existing DB encoding.
In my case DB is `utf8mb4_0900_ai_ci` and DMS tables are `utf8mb4_unicode_ci`

Whatever, error remains after re-endoding DB in `utf8mb4_unicode_ci` and I don't understand why...

**Comment by Mimetis** [comment] 2021-02-26 19:12
Did u tried with last prerelease version , and a fresh new database ?

**Comment by Mimetis** [comment] 2021-03-02 08:43
Can we close this issue ?

**Comment by sylverbee** [comment] 2021-03-02 08:45
Have your tested on your side?

**Comment by Mimetis** [comment] 2021-03-02 08:49
Yes, but i don't have any problem with encoding.
You can find the tests I've written to ensure your issue is fixed in the next version `v0.6.3`:

https://github.com/Mimetis/Dotmim.Sync/blob/03fe4344ad51b21c2a424185d3f5cc982fed3493/Tests/Dotmim.Sync.Tests/TcpTests.cs#L3737

**Comment by sylverbee** [comment] 2021-03-02 08:52
Ok so let's close. If I get a new bug, I'll reopen. Thx

**Comment by sylverbee** [comment] 2021-03-09 09:30
I face again an issue with tables collation on mySQL.
MySQL is utf8mb4_0900_ai_ci and DMS creates tables uft8mb4_unicode_ci.

So DMS bugs

**Comment by Mimetis** [comment] 2021-03-09 10:17
`DMS` does not use any collation when creating table.

When you are creating the Client database, are you specifying the collation ?
Something like
``` sql
CREATE DATABASE Client
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;
```

**Comment by sylverbee** [comment] 2021-03-09 12:42
In SQLite, `PRAGMA encoding="UTF-8"`.
I updated mySQL to have only `UTF8mb4_unicode_ci`.

**Comment by Mimetis** [comment] 2021-03-09 12:56
How do you see that the traking table are created with this collation ?
I'm trying to reproduce

**Comment by sylverbee** [comment] 2021-03-09 12:58
That's what I see from dbase.

![Capture d’écran 2021-03-09 135825](https://user-images.githubusercontent.com/78860181/110474089-8d342800-80df-11eb-9611-250abbe1796f.jpg)

**Comment by Mimetis** [comment] 2021-03-09 13:21
I don't know what to say ...
Here is a screenshot of my tests. Everything (generated by `DMS` or not) have the correct collation ...

**Tables**:
![image](https://user-images.githubusercontent.com/4592555/110476680-8955d500-80e2-11eb-87f1-0ab649aeb6cf.png)

**Columns**:
![image](https://user-images.githubusercontent.com/4592555/110476772-a8546700-80e2-11eb-853a-e6e910f98063.png)

Can you please try with the docker image we are using for testing ?

``` sh
docker run --name mysql -e MYSQL_ROOT_PASSWORD=Password12! -p 3307:3306 -d mysql
```

And see if the results are different ?

**Comment by sylverbee** [comment] 2021-03-09 16:32
For my understanding => your db (server) is UFT8mb4_0900_ai_ci?

**Comment by Mimetis** [comment] 2021-03-09 16:39
everything is `UFT8mb4_0900_ai_ci` on my side

Did you tried with the docker image ?

**Comment by sylverbee** [comment] 2021-03-09 16:56
Everything was also UFT8mb4_0900_ai_ci on my side before.
Is there any specifity to apply on SQLite?

**Comment by Mimetis** [comment] 2021-03-09 17:03
No, I don't think so.
That's weird.. I don't see the differences between us...

**Comment by sylverbee** [comment] 2021-03-09 17:32
Yep...
Just a question : is **collation_connection**	crucial for DMS?
Because I can set up server only on `utf8mb4_general_ci` or `utf8mb4_0900_ai_ci.`

One solution could be to switch mySQL back to `utf8mb4_0900_ai_ci`.

**Comment by Mimetis** [comment] 2021-03-09 18:23
I don't know, I'm not a MySql specialist :) 
I guess you have to try !

Maybe you should see these 2 Issues in `MySqlConnector`:

https://github.com/mysql-net/MySqlConnector/issues/585
https://github.com/mysql-net/MySqlConnector/issues/626

If I understand correctly, `MySqlConnector` uses to the server's default connection collation for `utf8mb4`

**Comment by sylverbee** [comment] 2021-03-09 19:38
Yes I did and it works. Yes!


I totally rewrote all my classes to stop using SQLconnector. You mentioned this concern on another bug.

**Closed** 2021-03-10 07:55 UTC
