### ISSUE TITLE
Sync with a unique columns

### ISSUE THREAD

**Issue by ahmedpiosol** [Mimetis/Dotmim.Sync#44] opened 2018-03-05 08:06 UTC
i don't know if there is a solution for that 
but if i make any column a unique (Not the primary key) and tried to sync it server wins, client wins, filters, no filters it just go crazy with exceptions and cancel the sync process

i think if it insert a new row with a unique column and it's already there it should try to replace/update it depend on what ever server wins or client or at least give me the option to do so

**Comment by Mimetis** [comment] 2018-03-05 08:29
This is because, you should have a Unique constraint error from the synchronized database.

For instance:

Server Row (`Row 1`) : **P key** = A. **Unique Column** = B
Client Row  (`Row 2`) : **P Key** = C. **Unique Column** = B

If you tried a synchronization with this rows, the `Dotmim.Sync` framework will try to:

* Insert in the server side, the `Row 2'
* The server database will throw an exception `UniqueConstraintException` (or something like that)
* Send the error to the client
* Rollback the whole sync.

Is your the behavio you encounter ?

By the way, what do you think, could be a good solution ?

In my opinion, maybe, Ididn't test, but i deserves to be tested ;), you should try this:
* Replace the schema: One Primary Column and One Unique Column
* With this schema : One Primary column composed by two Column (primary column + unique column)

In this case, my first sample will work:

Server Row (`Row 1`) : **P key** [A + B]
Client Row  (`Row 2`) : **P Key** [C + B]

*Sync*

Server Row : **P key** [A + B]
Server Row:  **P key** [C + B]
Client Row : **P key** [A + B]
Client Row:  **P key** [C + B]

Make sense ?

**Comment by ahmedpiosol** [comment] 2018-03-05 11:11
> Is your the behavio you encounter ?
yes

> This is because, you should have a Unique constraint error from the synchronized database.
yes, but my point is the sync process should be the one to handle that depending on the user configs "replace or update client row if server wins - replace or update the server row if client wins  - replace update the old row with the new one in cause of an error" if i want to do so else throw the exception 

> Make sense ?
yeah that would work but in some cases composing the Primary and the Unique columns together could case problems i am trying to avoid in the first place with the unique index

**Comment by Mimetis** [comment] 2018-03-05 11:53
The problem is that there is no "conflict" because conflicts are based on primary keys resolution.   
Let me think about that...

One idea could be to:

* Launch Sync
* Client send the rows.
* Server try to insert / update / delete
* Server error occured (in your case Unique Constraint, or sort of)
* Generating a conflict
* Ask the server how to resolve this conflict
* Apply resolve issue on server
* Send back the resolved row to client

Actually this is exactly what occured today when there is an `Insert` / `Update` / `Delete` conflict that occurs.
The fact is that there is no conflict generated when it's an `Error` conflict

I will make some tests in that way

**Comment by ahmedpiosol** [comment] 2018-03-19 07:27
any progress?!

**Comment by Mimetis** [comment] 2018-03-19 07:44
Will probably working on this feature this week.

**Comment by ahmedflix25** [comment] 2018-06-09 16:21
I hit that wall too, any progress lately or a way to help?

**Comment by Mimetis** [comment] 2018-06-17 14:28
I can't find a way to resolve this.
The problem is that the server and the client row does not have the same ID.
I think this problem can't be resolved from the sync fx perspective.
I'm working on it, but I think I won't be able to find a correct solution...

**Comment by ahmedflix25** [comment] 2018-06-17 18:57
i think the only correct solution here is to give the developer multi-options to choose what works with him the best
options like
1- Server Wins
    a- replace every row from the client that had error with a unique index
    b- replace every row from the client that had error with a unique index but the primary id
2- Client Wins
    a- replace every row from the server that had error with a unique index
    b- replace every row from the server that had error with a unique index but the primary id

Continue sync the new replaced stuff back and forth

**Comment by Mimetis** [comment] 2018-06-18 08:31
Hey @ahmedflix25, @ahmedpiosol .  
I've just spent a lot of time on this issue.  

Here is what I've done so far. Imagine we have 2 databases with 1 table, with 1 unique key constraint, as you expect.
Here are the datas, *before* sync:  

** Server **
`Key` 'E26E6345' - `UniqueID` '**A**' - `Text` : 'Row with unique value A'
** Slave **
`Key` 'DE3E9845' - `UniqueID` '**A**' - `Text` : 'Row with unique value A'

As we can expect, the server will throw a **Unique key constraint exception**

To be able to make it work, for now, you will have to:
- Disable the `UseBulkOperations` options : `agent.Configuration.UseBulkOperations = false;` : This is mandatory since the bulk mode is *everything or nothing commited*. 
- Use the merge row technic to merge the two rows in conflicts:
```
agent.ApplyChangedFailed += (s, args) =>
{
   args.Action = ConflictAction.MergeRow;
   args.FinalRow["UniqueID"] = "A1";
};
```
In this case, the final result will be **2 available rows**, each one with the correct primary keys, and one (the client row, updated with a new unique id):

** Server **
`Key` 'E26E6345' - `UniqueID` '**A**' - `Text` : 'Row with unique value A'
`Key` 'DE3E9845' - `UniqueID` '**A1**' - `Text` : 'Row with unique value A'
** Slave **
`Key` 'E26E6345' - `UniqueID` '**A**' - `Text` : 'Row with unique value A'
`Key` 'DE3E9845' - `UniqueID` '**A1**' - `Text` : 'Row with unique value A'

**Comment by ahmedflix25** [comment] 2018-06-18 11:55
let's say you have Users table with `id (primary), name(unique), pass, email` with this row on the server and client
`1,name,pass,email`
and a Logs table with `id, date, userid`
changing the password for example to pass1 on the client database and sync it to server
if the final rows ended up like this on the server
`1,name,pass,email`
`2,name1,pass1,email`
that will cause problems with foreign keys because you will end up with 2 different users with 2 different results in the Logs table
but if it was like this after the sync 
`1,name,pass1,email`
`2,name1,pass1,email`
i think that's might work

**Comment by Mimetis** [comment] 2018-06-26 15:49
Hey @ahmedflix25 
I 've applied the fix on the last version 0.2.1
Can you make a try ?

**Comment by ahmedflix25** [comment] 2018-06-26 16:03
sure, i will test it now

**Comment by ahmedflix25** [comment] 2018-06-26 23:50
@Mimetis using
`agent.ApplyChangedFailed += (s, args) =>
{
   args.Action = ConflictAction.MergeRow;
   args.FinalRow["UniqueID"] = "A1";
};`

or 

`agent.ApplyChangedFailed += (s, args) =>
            {
                args.Action = ConflictAction.ClientWins;
            };`

works the problem that it replaces the whole table with the conflict not just the specific row with the problem

(i seed the data to the database via management studio before the sync and uses GUID as primary key)

**Comment by Mimetis** [comment] 2018-06-27 13:28
Okey, can you send me a little repro ?

**Comment by ahmedflix25** [comment] 2018-06-27 13:30
will see what i can do

**Comment by Hadronicus** [comment] 2018-06-30 16:01
This scenario actually seems like it would be very common on any database that has unique constraints on each table’s natural key but uses a surrogate key as a primary/synchronization key.

In general, you can solve this problem by adding an additional “key change” step to the synchronization process that occurs before syncing change data. You have to be able to detect key change conflicts first which requires the sync process to have knowledge of the unique constraints for each table. This knowledge could be stored statically as part of the provisioning or it could be determined dynamically through the metadata catalogue of the database provider. Key change conflicts can then be detected by comparing client and server tables based on the unique constraint to find any records where the primary/synchronization key differs between the two databases. 

If any key change conflicts are detected, they can be resolved by updating the primary/synchronization key on either the client or server (probably best to do it on the client, but you could make it configurable just like any other conflict resolution policy). This change would need to be propagated to the metadata tracking tables as well as any foreign key referenced. 

This process can have a cascading effect if, for example, a table with a foreign key reference uses that foreign key as part of a composite primary key. In this case, the metadata tracking table for the dependent table would need to be updated to reflect this change as well.

You also would have to be careful to not accidentally invalidate any of the change tracking metadata to make the key change resolution appear to be a local change. This could result in update conflicts when applying changes during the rest of the sync process. It would probably be best to disable change tracking triggers during this step and handle the metadata updates manually as part of they key change process. 

Once all of they key change conflicts have been resolved, the inserts, updates, and deletes can then be processed normally. 

All of this is assuming that the underlying database is reasonably well designed and that updating the primary key based on a collision with one inquiry constraints will not violate another unique constraints on that table. In this case, the problem is likely a schema design problem and not a synchronization problem.

**Comment by ahmedflix25** [comment] 2018-07-13 15:41
sorry for the late response

at first running of the app it will ask you about the connection info for the server and the client db and it need dot net framework 4.6.2 or later

to edit a user in the client db double click it on the datagrid then go to add/edit tab

https://github.com/ahmedflix25/SyncTest

**Closed** 2018-09-08 17:14 UTC

**Comment by ManSchw** [comment] 2020-07-09 10:23
Hi, i am also running into the same problem

You closed the issue in 2018.. does this mean that the problem is fixed now?

**Comment by Mimetis** [comment] 2020-07-09 10:57
Can you provide more context ?

**Comment by ManSchw** [comment] 2020-07-09 11:05
Sure

I have a SQL Server table with primary key and an additional unique column called "UniqueIdentifier".
If I create a new table entry on a client with, lets say, "UniqueIdentifier" = XYZ, and another table entry on the server with the exact same "UniqueIdentifier" XYZ, then i get an exception: "Dotmim.Sync.SyncException: Cannot insert duplicate key row in object"

Is there a way to solve this problem?

**Comment by Mimetis** [comment] 2020-07-09 11:56
This is because, you should have a Unique constraint error from the synchronized database.

For instance, do you have this kind of rows ? :

Server Row (`Row 1`) : **P key** = A. **Unique Column** = B
Client Row  (`Row 2`) : **P Key** = C. **Unique Column** = B

In that case, it's normal you have a duplicate row error.

**Comment by ManSchw** [comment] 2020-07-09 12:06
Yes, i have this exact situation

Is there a way to keep both rows by setting one of the Unique columns to null?

**Comment by Mimetis** [comment] 2020-07-09 12:49
In that case you will have two different rows in both datasources, and we don't want that, since it will not be "synchronized" anymore (2 differents rows)

Your best fit is to disable the unique constraint I guess
