### ISSUE TITLE
Microsoft SQL Server 2017 under Linux produces doubled SQL column names

### ISSUE THREAD

**Issue by xafero** [Mimetis/Dotmim.Sync#144] opened 2019-02-17 15:42 UTC
The method "Dotmim.Sync.SqlServer.SqlManagementUtils.ColumnsForTable" runs a specific SQL statement to get all the column names of a table. But on the current 2017 version it runs doubled columns for all, for example 34 columns instead of 17 and "ProductId" two times. 
So, running your example from the first page, syncing everything to SQLite does not work because SQLite does not like that.

**Comment by xafero** [comment] 2019-02-17 15:48
name	column_id	type	max_length	precision	scale	is_nullable	is_computed	is_identity	is_unique
Color	4	nvarchar	30	0	0	true	false	false	<null>
Color	4	nvarchar	30	0	0	true	false	false	true

I guess, one reason is having a join which can result in "is_unique" null & true at the same time.

**Comment by Mimetis** [comment] 2019-02-18 00:22
can you share your code ?

**Comment by xafero** [comment] 2019-02-18 06:58
https://github.com/Mimetis/Dotmim.Sync/blob/master/Readme.md#how-it-works

(DB: SQL Server Linux 2017, Data: AdventureWorksLT2017)

On February 18, 2019 1:22:09 AM GMT+01:00, "Sébastien Pertus" <notifications@github.com> wrote:

can you share your code ?

**Comment by Mimetis** [comment] 2019-02-18 08:49
Hello @xafero 
I've just tested on my machine with an image from https://hub.docker.com/_/microsoft-mssql-server, using the latest `2017` image

On my machine everything is synced correctly, on a **Sqlite** database, acting as the client of the sync process.

I need more information I guess. Do you think about something special I didn't do yet on my sample ?

Seb

**Comment by xafero** [comment] 2019-02-18 09:23
I'm using

https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2017.bak

Additionally, do you mind running the SQL query embedded in the method I've wrote about?

**Comment by Mimetis** [comment] 2019-02-18 14:46
So far, I have restored the backup on a `SQL Server 2017` docker Linux image.   
Then I've takien thes generated query from:
``` csharp
public static DmTable ColumnsForTable(SqlConnection connection, SqlTransaction transaction, string tableName)
        {
        }
```
Here is the TSQL statement I used :

``` sql
Select tbl.name, col.name as name, col.column_id, typ.name as [type], col.max_length, col.precision, col.scale, col.is_nullable, col.is_computed, col.is_identity, ind.is_unique
from sys.columns as col
Inner join sys.tables as tbl on tbl.object_id = col.object_id 
Inner Join sys.systypes typ on typ.xusertype = col.system_type_id 
Left outer join sys.indexes ind on ind.object_id = col.object_id and ind.index_id = col.column_id 
order by tbl.name, col.name
```


The only table where there is a `Color` column (from your description) is the `Product` table.   
Here is what I have regarding this table:

| Table | Name | Id | [type] | max_length | precision | scale |  is_nullable | is_computed | is_identity | is_unique |
|---| ---| ---| --- | --- | --- | --- |  --- | ---| --- | --- |
| Product | Color | 4 | nvarchar | 30 | 0 | 0 | 1 | 0 | 0 | 1 |
| Product |	DiscontinuedDate |	13 |	datetime |	8 |	23 |	3 |	1 |	0 |	0 |	NULL |
| Product |	ListPrice | 	6 | 	money | 	8 | 	19 | 	4 | 	0 | 	0 | 	0 | 	NULL | 
| Product | 	ModifiedDate | 	17 | 	datetime | 	8 | 	23 | 	3 | 	0 | 	0 | 	0 | 	NULL | 
| Product | 	Name | 	2 | 	nvarchar | 	100 | 	0 | 	0	 | 0 | 	0	 | 0 | 	1 | 
| Product | 	ProductCategoryID | 	9 | 	int | 	4	 | 10 | 	0 | 	1 | 	0	 | 0 | 	NULL | 
...
| Product | 	StandardCost	 | 5	 | money | 	8	 | 19 | 	4 | 	0 | 	0	 | 0 | 	NULL | 
| Product | 	ThumbNailPhoto	 | 14 | 	varbinary | 	-1 | 	0 | 	0	 | 1 | 	0 | 	0	 | NULL | 
| Product | 	ThumbnailPhotoFileName | 	15	 | nvarchar	 | 100	 | 0 | 	0 | 	1	 | 0 | 	0	 | NULL | 
| Product | 	Weight | 	8	 | decimal	 | 5 | 	8 | 	2 | 	1 | 	0 | 	0 | 	NULL | 

So far, I don't have the `Color` columns multiple times...

Continuing my investigations.

**Comment by Mimetis** [comment] 2019-02-20 17:56
Hey @xafero 
I close this issue, since I'm not able to reproduce it.

If you have more information, do not hesitate to post here, I will re-open the issue then

Thx

**Closed by Mimetis** 2019-02-20 17:56 UTC
Labels: bug, investigation

**Comment by asanchez128** [comment] 2019-07-24 16:47
If I run the query "Select col.name as name, col.column_id, typ.name as [type], col.max_length, col.precision, col.scale, col.is_nullable, col.is_computed, col.is_identity, ind.is_unique from sys.columns as col Inner join sys.tables as tbl on tbl.object_id = col.object_id Inner Join sys.systypes typ on typ.xusertype = col.system_type_id Left outer join sys.indexes ind on ind.object_id = col.object_id and ind.index_id = col.column_id Where tbl.name = 'Address'" on SSMS 2017 on a Windows machine I get duplicated rows. Im using the AdventureWorks2017 database

**Comment by asanchez128** [comment] 2019-07-24 17:07
I haven't done it but based on my research my guess is that if you install twice the AdventureWorks database into the same instance you will be able to reproduce the bug.
