### ISSUE TITLE
Connection null utilizing TranscationMode.PerBatch

### ISSUE THREAD

**Issue by maprado-inetum** [Mimetis/Dotmim.Sync#882] opened 2022-11-26 12:02 UTC
Hi all.
I found this bug in the 'ProgressArgs' class when using the 'PerBatch' transaction type in the 'SyncOptions'.
When I want to trace the DataSource of the connection, the 'Connection' object is null after closing the connection when loading the scope.

SyncOptions with TranscationMode = PerBatch
![image](https://user-images.githubusercontent.com/79869950/204087613-83b4dd28-f982-4539-b1dd-be4747e6a8e6.png)

Error synchronizing
![image](https://user-images.githubusercontent.com/79869950/204087763-13d242b3-9efa-4696-8d6c-154b4fc6f2d0.png)
![image](https://user-images.githubusercontent.com/79869950/204087743-d665f14f-14fc-4226-a998-196f086644e4.png)

**Comment by Mimetis** [comment] 2022-11-26 13:10
When `Transaction` is set to `PerBatch`, the connection is opened and closed in between batches
So it's normal to have sometimes a `connection == null` during the progress.

It's not a bug from `DMS`, it's just up to you to test `if connection == null` in your progress

Make sense ?

**Comment by maprado-inetum** [comment] 2022-11-27 09:48
Ok, así lo haré. 
Pensé que eso se controlaba dentro del código del framework.
Gracias de nuevo. Un saludo

**Closed** 2022-11-27 09:50 UTC
